// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type SlackChannel struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
}

type SlackMessage struct {
	ID        int64  `json:"id"`
	ChannelID string `json:"channel_id"`
	Type      string `json:"type"`
	UserID    string `json:"user_id"`
	Text      string `json:"text"`
	Timestamp string `json:"timestamp"`
	CreatedAt int64  `json:"created_at"`
}
