// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: slack.sql

package database

import (
	"context"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO slack_messages (channel_id, type, user_id, text, timestamp)
VALUES (?, ?, ?, ?, ?)
`

type CreateMessageParams struct {
	ChannelID string `json:"channel_id"`
	Type      string `json:"type"`
	UserID    string `json:"user_id"`
	Text      string `json:"text"`
	Timestamp string `json:"timestamp"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.ChannelID,
		arg.Type,
		arg.UserID,
		arg.Text,
		arg.Timestamp,
	)
	return err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, name, created_at
FROM slack_channels
WHERE id = ?
`

func (q *Queries) GetChannelByID(ctx context.Context, id string) (SlackChannel, error) {
	row := q.db.QueryRowContext(ctx, getChannelByID, id)
	var i SlackChannel
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getMessagesByChannel = `-- name: GetMessagesByChannel :many
SELECT type, user_id, text, timestamp
FROM slack_messages
WHERE channel_id = ?
ORDER BY timestamp DESC
`

type GetMessagesByChannelRow struct {
	Type      string `json:"type"`
	UserID    string `json:"user_id"`
	Text      string `json:"text"`
	Timestamp string `json:"timestamp"`
}

func (q *Queries) GetMessagesByChannel(ctx context.Context, channelID string) ([]GetMessagesByChannelRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMessagesByChannelRow{}
	for rows.Next() {
		var i GetMessagesByChannelRow
		if err := rows.Scan(
			&i.Type,
			&i.UserID,
			&i.Text,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannels = `-- name: ListChannels :many
SELECT id, name, created_at
FROM slack_channels
ORDER BY created_at ASC
`

func (q *Queries) ListChannels(ctx context.Context) ([]SlackChannel, error) {
	rows, err := q.db.QueryContext(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlackChannel{}
	for rows.Next() {
		var i SlackChannel
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
