version: 2

run:
  timeout: 5m
  go: '1.23'
  tests: true
  skip-dirs:
    - vendor
    - node_modules

linters:
  enable:
    # Enabled by default
    - errcheck      # Check for unchecked errors
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis (includes gosimple)
    - unused        # Check for unused code

    # Additional recommended linters
    - misspell      # Finds commonly misspelled words
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Reports unused function parameters
    - gosec         # Security problems
    - bodyclose     # Check HTTP response body is closed
    - noctx         # Finds sending http request without context.Context
    - sqlclosecheck # Check sql.Rows and sql.Stmt are closed
    - rowserrcheck  # Check whether Err of rows is checked
    - copyloopvar   # Check for loop variable copies (replaces exportloopref)
    - goconst       # Repeated strings that could be constants
    - gocritic      # Opinionated Go linter
    - errname       # Check error names (should be ErrXxx or xxxError)
    - errorlint     # Find misuses of errors
    - makezero      # Finds slice declarations with non-zero initial length
    - nilerr        # Finds code returning nil even if it checks error != nil
    - nilnil        # Checks no simultaneous return of nil error and nil value
    - predeclared   # Finds shadowing of predeclared identifiers
    - thelper       # Detects test helpers without t.Helper()
    - tparallel     # Detects inappropriate usage of t.Parallel()
    - wastedassign  # Finds wasted assignment statements
    - whitespace    # Detection of leading/trailing whitespace

    # Additional quality & style linters
    - dogsled       # Flags excessive blank identifiers
    - dupword       # Detects duplicate words (with autofix)
    - usestdlibvars # Use stdlib constants (http.StatusOK vs 200)

    # Performance
    - prealloc      # Pre-allocate slices for better performance

    # Security
    - bidichk       # Detects dangerous Unicode sequences

    # Code readability
    - funlen        # Enforces readable function length limits

    # SQL-specific (for sqlc usage)
    - unqueryvet    # Detects SELECT * in SQL queries

    # Testing (testify library)
    - testifylint   # Enforces testify best practices

    # Type safety
    - forcetypeassert # Forbids unsafe type assertions without comma-ok idiom

  settings:
    errcheck:
      # Don't check for errors on these functions (as per CLAUDE.md)
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - (net/http.ResponseWriter).Write
        - (*net/http.Response.Body).Close
        - (*encoding/json.Encoder).Encode
        - (*net/http.Server).Shutdown
        - os.Setenv
        - os.Unsetenv

    gocyclo:
      min-complexity: 15

    gocognit:
      min-complexity: 20

    goconst:
      min-len: 3
      min-occurrences: 3

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - hugeParam  # Early stage, optimize later
        - typeDefFirst  # Conflicts with generated code

    stylecheck:
      checks: ["all", "-ST1000", "-ST1003", "-ST1016"]

    funlen:
      lines: 200             # Maximum lines per function (default: 60)
      statements: 100           # Maximum statements per function (default: 40)
      ignore-comments: true    # Ignore comment lines when counting (default: false)

    dogsled:
      max-blank-identifiers: 2

    revive:
      severity: warning
      enable-all-rules: false
      rules:
        - name: var-naming
        - name: exported
        - name: indent-error-flow
        - name: error-return
        - name: error-strings
        - name: receiver-naming

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - goconst

    # Exclude linters for generated code
    - path: ".*\\.gen\\.go$"
      linters:
        - all

    # Exclude sqlc generated code
    - path: "internal/db/.*\\.sql\\.go$"
      linters:
        - all

    # Exclude app_data.go (generated models)
    - path: "internal/models/app_data\\.go$"
      linters:
        - all

    # Exclude openapi_types.go (generated API types)
    - path: "internal/models/openapi_types\\.go$"
      linters:
        - all

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
