// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: datadog.sql

package database

import (
	"context"
	"database/sql"
)

const createDatadogEvent = `-- name: CreateDatadogEvent :one

INSERT INTO datadog_events (title, text, tags, session_id, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, title, text, tags, created_at
`

type CreateDatadogEventParams struct {
	Title     string         `json:"title"`
	Text      string         `json:"text"`
	Tags      sql.NullString `json:"tags"`
	SessionID string         `json:"session_id"`
	CreatedAt int64          `json:"created_at"`
}

type CreateDatadogEventRow struct {
	ID        int64          `json:"id"`
	Title     string         `json:"title"`
	Text      string         `json:"text"`
	Tags      sql.NullString `json:"tags"`
	CreatedAt int64          `json:"created_at"`
}

// Events (v1 API)
func (q *Queries) CreateDatadogEvent(ctx context.Context, arg CreateDatadogEventParams) (CreateDatadogEventRow, error) {
	row := q.db.QueryRowContext(ctx, createDatadogEvent,
		arg.Title,
		arg.Text,
		arg.Tags,
		arg.SessionID,
		arg.CreatedAt,
	)
	var i CreateDatadogEventRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Text,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const createDatadogIncident = `-- name: CreateDatadogIncident :exec

INSERT INTO datadog_incidents (id, title, customer_impacted, severity, session_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateDatadogIncidentParams struct {
	ID               string         `json:"id"`
	Title            string         `json:"title"`
	CustomerImpacted int64          `json:"customer_impacted"`
	Severity         sql.NullString `json:"severity"`
	SessionID        string         `json:"session_id"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

// Incidents (v2 API)
func (q *Queries) CreateDatadogIncident(ctx context.Context, arg CreateDatadogIncidentParams) error {
	_, err := q.db.ExecContext(ctx, createDatadogIncident,
		arg.ID,
		arg.Title,
		arg.CustomerImpacted,
		arg.Severity,
		arg.SessionID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createDatadogMetric = `-- name: CreateDatadogMetric :exec

INSERT INTO datadog_metrics (metric_name, value, tags, timestamp, session_id, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateDatadogMetricParams struct {
	MetricName string         `json:"metric_name"`
	Value      float64        `json:"value"`
	Tags       sql.NullString `json:"tags"`
	Timestamp  int64          `json:"timestamp"`
	SessionID  string         `json:"session_id"`
	CreatedAt  int64          `json:"created_at"`
}

// Metrics (v2 API)
func (q *Queries) CreateDatadogMetric(ctx context.Context, arg CreateDatadogMetricParams) error {
	_, err := q.db.ExecContext(ctx, createDatadogMetric,
		arg.MetricName,
		arg.Value,
		arg.Tags,
		arg.Timestamp,
		arg.SessionID,
		arg.CreatedAt,
	)
	return err
}

const createDatadogMonitor = `-- name: CreateDatadogMonitor :one

INSERT INTO datadog_monitors (name, type, query, message, session_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, type, query, message, created_at, updated_at
`

type CreateDatadogMonitorParams struct {
	Name      string         `json:"name"`
	Type      string         `json:"type"`
	Query     string         `json:"query"`
	Message   sql.NullString `json:"message"`
	SessionID string         `json:"session_id"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

type CreateDatadogMonitorRow struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Type      string         `json:"type"`
	Query     string         `json:"query"`
	Message   sql.NullString `json:"message"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

// Monitors (v1 API)
func (q *Queries) CreateDatadogMonitor(ctx context.Context, arg CreateDatadogMonitorParams) (CreateDatadogMonitorRow, error) {
	row := q.db.QueryRowContext(ctx, createDatadogMonitor,
		arg.Name,
		arg.Type,
		arg.Query,
		arg.Message,
		arg.SessionID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateDatadogMonitorRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Query,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDatadogMonitor = `-- name: DeleteDatadogMonitor :exec
DELETE FROM datadog_monitors
WHERE id = ? AND session_id = ?
`

type DeleteDatadogMonitorParams struct {
	ID        int64  `json:"id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) DeleteDatadogMonitor(ctx context.Context, arg DeleteDatadogMonitorParams) error {
	_, err := q.db.ExecContext(ctx, deleteDatadogMonitor, arg.ID, arg.SessionID)
	return err
}

const deleteDatadogSessionData = `-- name: DeleteDatadogSessionData :exec

DELETE FROM datadog_incidents WHERE session_id = ?
`

// Cleanup
func (q *Queries) DeleteDatadogSessionData(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteDatadogSessionData, sessionID)
	return err
}

const getDatadogEventByID = `-- name: GetDatadogEventByID :one
SELECT id, title, text, tags, created_at
FROM datadog_events
WHERE id = ? AND session_id = ?
`

type GetDatadogEventByIDParams struct {
	ID        int64  `json:"id"`
	SessionID string `json:"session_id"`
}

type GetDatadogEventByIDRow struct {
	ID        int64          `json:"id"`
	Title     string         `json:"title"`
	Text      string         `json:"text"`
	Tags      sql.NullString `json:"tags"`
	CreatedAt int64          `json:"created_at"`
}

func (q *Queries) GetDatadogEventByID(ctx context.Context, arg GetDatadogEventByIDParams) (GetDatadogEventByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDatadogEventByID, arg.ID, arg.SessionID)
	var i GetDatadogEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Text,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const getDatadogIncidentByID = `-- name: GetDatadogIncidentByID :one
SELECT id, title, customer_impacted, severity, session_id, created_at, updated_at
FROM datadog_incidents
WHERE id = ? AND session_id = ?
`

type GetDatadogIncidentByIDParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) GetDatadogIncidentByID(ctx context.Context, arg GetDatadogIncidentByIDParams) (DatadogIncident, error) {
	row := q.db.QueryRowContext(ctx, getDatadogIncidentByID, arg.ID, arg.SessionID)
	var i DatadogIncident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CustomerImpacted,
		&i.Severity,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDatadogMonitorByID = `-- name: GetDatadogMonitorByID :one
SELECT id, name, type, query, message, session_id, created_at, updated_at
FROM datadog_monitors
WHERE id = ? AND session_id = ?
`

type GetDatadogMonitorByIDParams struct {
	ID        int64  `json:"id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) GetDatadogMonitorByID(ctx context.Context, arg GetDatadogMonitorByIDParams) (DatadogMonitor, error) {
	row := q.db.QueryRowContext(ctx, getDatadogMonitorByID, arg.ID, arg.SessionID)
	var i DatadogMonitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Query,
		&i.Message,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDatadogEvents = `-- name: ListDatadogEvents :many
SELECT id, title, text, tags, created_at
FROM datadog_events
WHERE session_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListDatadogEventsParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
}

type ListDatadogEventsRow struct {
	ID        int64          `json:"id"`
	Title     string         `json:"title"`
	Text      string         `json:"text"`
	Tags      sql.NullString `json:"tags"`
	CreatedAt int64          `json:"created_at"`
}

func (q *Queries) ListDatadogEvents(ctx context.Context, arg ListDatadogEventsParams) ([]ListDatadogEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDatadogEvents, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDatadogEventsRow{}
	for rows.Next() {
		var i ListDatadogEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Text,
			&i.Tags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatadogIncidents = `-- name: ListDatadogIncidents :many
SELECT id, title, customer_impacted, severity, created_at, updated_at
FROM datadog_incidents
WHERE session_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListDatadogIncidentsParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
}

type ListDatadogIncidentsRow struct {
	ID               string         `json:"id"`
	Title            string         `json:"title"`
	CustomerImpacted int64          `json:"customer_impacted"`
	Severity         sql.NullString `json:"severity"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

func (q *Queries) ListDatadogIncidents(ctx context.Context, arg ListDatadogIncidentsParams) ([]ListDatadogIncidentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDatadogIncidents, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDatadogIncidentsRow{}
	for rows.Next() {
		var i ListDatadogIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CustomerImpacted,
			&i.Severity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatadogMetrics = `-- name: ListDatadogMetrics :many
SELECT id, metric_name, value, tags, timestamp, created_at
FROM datadog_metrics
WHERE session_id = ? AND metric_name = ?
ORDER BY timestamp DESC
LIMIT ?
`

type ListDatadogMetricsParams struct {
	SessionID  string `json:"session_id"`
	MetricName string `json:"metric_name"`
	Limit      int64  `json:"limit"`
}

type ListDatadogMetricsRow struct {
	ID         int64          `json:"id"`
	MetricName string         `json:"metric_name"`
	Value      float64        `json:"value"`
	Tags       sql.NullString `json:"tags"`
	Timestamp  int64          `json:"timestamp"`
	CreatedAt  int64          `json:"created_at"`
}

func (q *Queries) ListDatadogMetrics(ctx context.Context, arg ListDatadogMetricsParams) ([]ListDatadogMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDatadogMetrics, arg.SessionID, arg.MetricName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDatadogMetricsRow{}
	for rows.Next() {
		var i ListDatadogMetricsRow
		if err := rows.Scan(
			&i.ID,
			&i.MetricName,
			&i.Value,
			&i.Tags,
			&i.Timestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatadogMetricsBySession = `-- name: ListDatadogMetricsBySession :many
SELECT id, metric_name, value, tags, timestamp, created_at
FROM datadog_metrics
WHERE session_id = ?
ORDER BY timestamp DESC
LIMIT ?
`

type ListDatadogMetricsBySessionParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
}

type ListDatadogMetricsBySessionRow struct {
	ID         int64          `json:"id"`
	MetricName string         `json:"metric_name"`
	Value      float64        `json:"value"`
	Tags       sql.NullString `json:"tags"`
	Timestamp  int64          `json:"timestamp"`
	CreatedAt  int64          `json:"created_at"`
}

func (q *Queries) ListDatadogMetricsBySession(ctx context.Context, arg ListDatadogMetricsBySessionParams) ([]ListDatadogMetricsBySessionRow, error) {
	rows, err := q.db.QueryContext(ctx, listDatadogMetricsBySession, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDatadogMetricsBySessionRow{}
	for rows.Next() {
		var i ListDatadogMetricsBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.MetricName,
			&i.Value,
			&i.Tags,
			&i.Timestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatadogMonitors = `-- name: ListDatadogMonitors :many
SELECT id, name, type, query, message, created_at, updated_at
FROM datadog_monitors
WHERE session_id = ?
ORDER BY created_at DESC
`

type ListDatadogMonitorsRow struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Type      string         `json:"type"`
	Query     string         `json:"query"`
	Message   sql.NullString `json:"message"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

func (q *Queries) ListDatadogMonitors(ctx context.Context, sessionID string) ([]ListDatadogMonitorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDatadogMonitors, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDatadogMonitorsRow{}
	for rows.Next() {
		var i ListDatadogMonitorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Query,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDatadogIncident = `-- name: UpdateDatadogIncident :exec
UPDATE datadog_incidents
SET title = COALESCE(?1, title),
    customer_impacted = COALESCE(?2, customer_impacted),
    severity = COALESCE(?3, severity),
    updated_at = ?4
WHERE id = ?5 AND session_id = ?6
`

type UpdateDatadogIncidentParams struct {
	Title            sql.NullString `json:"title"`
	CustomerImpacted sql.NullInt64  `json:"customer_impacted"`
	Severity         sql.NullString `json:"severity"`
	UpdatedAt        int64          `json:"updated_at"`
	ID               string         `json:"id"`
	SessionID        string         `json:"session_id"`
}

func (q *Queries) UpdateDatadogIncident(ctx context.Context, arg UpdateDatadogIncidentParams) error {
	_, err := q.db.ExecContext(ctx, updateDatadogIncident,
		arg.Title,
		arg.CustomerImpacted,
		arg.Severity,
		arg.UpdatedAt,
		arg.ID,
		arg.SessionID,
	)
	return err
}

const updateDatadogMonitor = `-- name: UpdateDatadogMonitor :exec
UPDATE datadog_monitors
SET name = COALESCE(?1, name),
    query = COALESCE(?2, query),
    message = COALESCE(?3, message),
    updated_at = ?4
WHERE id = ?5 AND session_id = ?6
`

type UpdateDatadogMonitorParams struct {
	Name      sql.NullString `json:"name"`
	Query     sql.NullString `json:"query"`
	Message   sql.NullString `json:"message"`
	UpdatedAt int64          `json:"updated_at"`
	ID        int64          `json:"id"`
	SessionID string         `json:"session_id"`
}

func (q *Queries) UpdateDatadogMonitor(ctx context.Context, arg UpdateDatadogMonitorParams) error {
	_, err := q.db.ExecContext(ctx, updateDatadogMonitor,
		arg.Name,
		arg.Query,
		arg.Message,
		arg.UpdatedAt,
		arg.ID,
		arg.SessionID,
	)
	return err
}
