// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gdocs.sql

package database

import (
	"context"
)

const createGdocsContent = `-- name: CreateGdocsContent :exec
INSERT INTO gdocs_content (document_id, content_json, end_index, session_id)
VALUES (?, ?, ?, ?)
`

type CreateGdocsContentParams struct {
	DocumentID  string `json:"document_id"`
	ContentJson string `json:"content_json"`
	EndIndex    int64  `json:"end_index"`
	SessionID   string `json:"session_id"`
}

func (q *Queries) CreateGdocsContent(ctx context.Context, arg CreateGdocsContentParams) error {
	_, err := q.db.ExecContext(ctx, createGdocsContent,
		arg.DocumentID,
		arg.ContentJson,
		arg.EndIndex,
		arg.SessionID,
	)
	return err
}

const createGdocsDocument = `-- name: CreateGdocsDocument :exec
INSERT INTO gdocs_documents (id, title, revision_id, document_id, session_id)
VALUES (?, ?, ?, ?, ?)
`

type CreateGdocsDocumentParams struct {
	ID         string `json:"id"`
	Title      string `json:"title"`
	RevisionID string `json:"revision_id"`
	DocumentID string `json:"document_id"`
	SessionID  string `json:"session_id"`
}

func (q *Queries) CreateGdocsDocument(ctx context.Context, arg CreateGdocsDocumentParams) error {
	_, err := q.db.ExecContext(ctx, createGdocsDocument,
		arg.ID,
		arg.Title,
		arg.RevisionID,
		arg.DocumentID,
		arg.SessionID,
	)
	return err
}

const deleteGdocsSessionData = `-- name: DeleteGdocsSessionData :exec
DELETE FROM gdocs_documents WHERE session_id = ?
`

func (q *Queries) DeleteGdocsSessionData(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteGdocsSessionData, sessionID)
	return err
}

const getGdocsContentByDocumentID = `-- name: GetGdocsContentByDocumentID :one
SELECT document_id, content_json, end_index, session_id, created_at, updated_at
FROM gdocs_content
WHERE document_id = ? AND session_id = ?
`

type GetGdocsContentByDocumentIDParams struct {
	DocumentID string `json:"document_id"`
	SessionID  string `json:"session_id"`
}

func (q *Queries) GetGdocsContentByDocumentID(ctx context.Context, arg GetGdocsContentByDocumentIDParams) (GdocsContent, error) {
	row := q.db.QueryRowContext(ctx, getGdocsContentByDocumentID, arg.DocumentID, arg.SessionID)
	var i GdocsContent
	err := row.Scan(
		&i.DocumentID,
		&i.ContentJson,
		&i.EndIndex,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGdocsDocumentByID = `-- name: GetGdocsDocumentByID :one
SELECT id, title, revision_id, document_id, session_id, created_at
FROM gdocs_documents
WHERE document_id = ? AND session_id = ?
`

type GetGdocsDocumentByIDParams struct {
	DocumentID string `json:"document_id"`
	SessionID  string `json:"session_id"`
}

func (q *Queries) GetGdocsDocumentByID(ctx context.Context, arg GetGdocsDocumentByIDParams) (GdocsDocument, error) {
	row := q.db.QueryRowContext(ctx, getGdocsDocumentByID, arg.DocumentID, arg.SessionID)
	var i GdocsDocument
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.RevisionID,
		&i.DocumentID,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const listGdocsBySession = `-- name: ListGdocsBySession :many
SELECT id, title, revision_id, document_id, created_at
FROM gdocs_documents
WHERE session_id = ?
ORDER BY created_at DESC
`

type ListGdocsBySessionRow struct {
	ID         string `json:"id"`
	Title      string `json:"title"`
	RevisionID string `json:"revision_id"`
	DocumentID string `json:"document_id"`
	CreatedAt  int64  `json:"created_at"`
}

// UI data queries
func (q *Queries) ListGdocsBySession(ctx context.Context, sessionID string) ([]ListGdocsBySessionRow, error) {
	rows, err := q.db.QueryContext(ctx, listGdocsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGdocsBySessionRow{}
	for rows.Next() {
		var i ListGdocsBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.RevisionID,
			&i.DocumentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGdocsContent = `-- name: UpdateGdocsContent :exec
UPDATE gdocs_content
SET content_json = ?, end_index = ?, updated_at = unixepoch()
WHERE document_id = ? AND session_id = ?
`

type UpdateGdocsContentParams struct {
	ContentJson string `json:"content_json"`
	EndIndex    int64  `json:"end_index"`
	DocumentID  string `json:"document_id"`
	SessionID   string `json:"session_id"`
}

func (q *Queries) UpdateGdocsContent(ctx context.Context, arg UpdateGdocsContentParams) error {
	_, err := q.db.ExecContext(ctx, updateGdocsContent,
		arg.ContentJson,
		arg.EndIndex,
		arg.DocumentID,
		arg.SessionID,
	)
	return err
}
