// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github.sql

package database

import (
	"context"
	"database/sql"
)

const createGithubBranch = `-- name: CreateGithubBranch :exec

INSERT INTO github_branches (repo_owner, repo_name, name, sha, session_id)
VALUES (?, ?, ?, ?, ?)
`

type CreateGithubBranchParams struct {
	RepoOwner string `json:"repo_owner"`
	RepoName  string `json:"repo_name"`
	Name      string `json:"name"`
	Sha       string `json:"sha"`
	SessionID string `json:"session_id"`
}

// Branch queries
func (q *Queries) CreateGithubBranch(ctx context.Context, arg CreateGithubBranchParams) error {
	_, err := q.db.ExecContext(ctx, createGithubBranch,
		arg.RepoOwner,
		arg.RepoName,
		arg.Name,
		arg.Sha,
		arg.SessionID,
	)
	return err
}

const createGithubIssue = `-- name: CreateGithubIssue :one

INSERT INTO github_issues (repo_owner, repo_name, number, title, body, state, session_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, repo_owner, repo_name, number, title, body, state, created_at, updated_at
`

type CreateGithubIssueParams struct {
	RepoOwner string         `json:"repo_owner"`
	RepoName  string         `json:"repo_name"`
	Number    int64          `json:"number"`
	Title     string         `json:"title"`
	Body      sql.NullString `json:"body"`
	State     string         `json:"state"`
	SessionID string         `json:"session_id"`
}

type CreateGithubIssueRow struct {
	ID        int64          `json:"id"`
	RepoOwner string         `json:"repo_owner"`
	RepoName  string         `json:"repo_name"`
	Number    int64          `json:"number"`
	Title     string         `json:"title"`
	Body      sql.NullString `json:"body"`
	State     string         `json:"state"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

// Issue queries
func (q *Queries) CreateGithubIssue(ctx context.Context, arg CreateGithubIssueParams) (CreateGithubIssueRow, error) {
	row := q.db.QueryRowContext(ctx, createGithubIssue,
		arg.RepoOwner,
		arg.RepoName,
		arg.Number,
		arg.Title,
		arg.Body,
		arg.State,
		arg.SessionID,
	)
	var i CreateGithubIssueRow
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGithubIssueComment = `-- name: CreateGithubIssueComment :one

INSERT INTO github_issue_comments (repo_owner, repo_name, issue_number, comment_id, body, session_id)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, repo_owner, repo_name, issue_number, comment_id, body, created_at
`

type CreateGithubIssueCommentParams struct {
	RepoOwner   string `json:"repo_owner"`
	RepoName    string `json:"repo_name"`
	IssueNumber int64  `json:"issue_number"`
	CommentID   int64  `json:"comment_id"`
	Body        string `json:"body"`
	SessionID   string `json:"session_id"`
}

type CreateGithubIssueCommentRow struct {
	ID          int64  `json:"id"`
	RepoOwner   string `json:"repo_owner"`
	RepoName    string `json:"repo_name"`
	IssueNumber int64  `json:"issue_number"`
	CommentID   int64  `json:"comment_id"`
	Body        string `json:"body"`
	CreatedAt   int64  `json:"created_at"`
}

// Issue Comment queries
func (q *Queries) CreateGithubIssueComment(ctx context.Context, arg CreateGithubIssueCommentParams) (CreateGithubIssueCommentRow, error) {
	row := q.db.QueryRowContext(ctx, createGithubIssueComment,
		arg.RepoOwner,
		arg.RepoName,
		arg.IssueNumber,
		arg.CommentID,
		arg.Body,
		arg.SessionID,
	)
	var i CreateGithubIssueCommentRow
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.IssueNumber,
		&i.CommentID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const createGithubPullRequest = `-- name: CreateGithubPullRequest :one

INSERT INTO github_pull_requests (repo_owner, repo_name, number, title, body, head, base, state, session_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, repo_owner, repo_name, number, title, body, head, base, state, merged, created_at, updated_at
`

type CreateGithubPullRequestParams struct {
	RepoOwner string         `json:"repo_owner"`
	RepoName  string         `json:"repo_name"`
	Number    int64          `json:"number"`
	Title     string         `json:"title"`
	Body      sql.NullString `json:"body"`
	Head      string         `json:"head"`
	Base      string         `json:"base"`
	State     string         `json:"state"`
	SessionID string         `json:"session_id"`
}

type CreateGithubPullRequestRow struct {
	ID        int64          `json:"id"`
	RepoOwner string         `json:"repo_owner"`
	RepoName  string         `json:"repo_name"`
	Number    int64          `json:"number"`
	Title     string         `json:"title"`
	Body      sql.NullString `json:"body"`
	Head      string         `json:"head"`
	Base      string         `json:"base"`
	State     string         `json:"state"`
	Merged    int64          `json:"merged"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

// Pull Request queries
func (q *Queries) CreateGithubPullRequest(ctx context.Context, arg CreateGithubPullRequestParams) (CreateGithubPullRequestRow, error) {
	row := q.db.QueryRowContext(ctx, createGithubPullRequest,
		arg.RepoOwner,
		arg.RepoName,
		arg.Number,
		arg.Title,
		arg.Body,
		arg.Head,
		arg.Base,
		arg.State,
		arg.SessionID,
	)
	var i CreateGithubPullRequestRow
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.Head,
		&i.Base,
		&i.State,
		&i.Merged,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGithubRepository = `-- name: CreateGithubRepository :exec

INSERT INTO github_repositories (owner, name, default_branch, description, session_id)
VALUES (?, ?, ?, ?, ?)
`

type CreateGithubRepositoryParams struct {
	Owner         string         `json:"owner"`
	Name          string         `json:"name"`
	DefaultBranch string         `json:"default_branch"`
	Description   sql.NullString `json:"description"`
	SessionID     string         `json:"session_id"`
}

// Repository queries
func (q *Queries) CreateGithubRepository(ctx context.Context, arg CreateGithubRepositoryParams) error {
	_, err := q.db.ExecContext(ctx, createGithubRepository,
		arg.Owner,
		arg.Name,
		arg.DefaultBranch,
		arg.Description,
		arg.SessionID,
	)
	return err
}

const createGithubWorkflow = `-- name: CreateGithubWorkflow :exec

INSERT INTO github_workflows (repo_owner, repo_name, workflow_id, name, path, state, session_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateGithubWorkflowParams struct {
	RepoOwner  string `json:"repo_owner"`
	RepoName   string `json:"repo_name"`
	WorkflowID int64  `json:"workflow_id"`
	Name       string `json:"name"`
	Path       string `json:"path"`
	State      string `json:"state"`
	SessionID  string `json:"session_id"`
}

// Workflow queries
func (q *Queries) CreateGithubWorkflow(ctx context.Context, arg CreateGithubWorkflowParams) error {
	_, err := q.db.ExecContext(ctx, createGithubWorkflow,
		arg.RepoOwner,
		arg.RepoName,
		arg.WorkflowID,
		arg.Name,
		arg.Path,
		arg.State,
		arg.SessionID,
	)
	return err
}

const createGithubWorkflowRun = `-- name: CreateGithubWorkflowRun :one

INSERT INTO github_workflow_runs (repo_owner, repo_name, run_id, workflow_id, status, conclusion, head_branch, head_sha, session_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, repo_owner, repo_name, run_id, workflow_id, status, conclusion, head_branch, head_sha, created_at, updated_at
`

type CreateGithubWorkflowRunParams struct {
	RepoOwner  string         `json:"repo_owner"`
	RepoName   string         `json:"repo_name"`
	RunID      int64          `json:"run_id"`
	WorkflowID int64          `json:"workflow_id"`
	Status     string         `json:"status"`
	Conclusion sql.NullString `json:"conclusion"`
	HeadBranch sql.NullString `json:"head_branch"`
	HeadSha    sql.NullString `json:"head_sha"`
	SessionID  string         `json:"session_id"`
}

type CreateGithubWorkflowRunRow struct {
	ID         int64          `json:"id"`
	RepoOwner  string         `json:"repo_owner"`
	RepoName   string         `json:"repo_name"`
	RunID      int64          `json:"run_id"`
	WorkflowID int64          `json:"workflow_id"`
	Status     string         `json:"status"`
	Conclusion sql.NullString `json:"conclusion"`
	HeadBranch sql.NullString `json:"head_branch"`
	HeadSha    sql.NullString `json:"head_sha"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

// Workflow Run queries
func (q *Queries) CreateGithubWorkflowRun(ctx context.Context, arg CreateGithubWorkflowRunParams) (CreateGithubWorkflowRunRow, error) {
	row := q.db.QueryRowContext(ctx, createGithubWorkflowRun,
		arg.RepoOwner,
		arg.RepoName,
		arg.RunID,
		arg.WorkflowID,
		arg.Status,
		arg.Conclusion,
		arg.HeadBranch,
		arg.HeadSha,
		arg.SessionID,
	)
	var i CreateGithubWorkflowRunRow
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.RunID,
		&i.WorkflowID,
		&i.Status,
		&i.Conclusion,
		&i.HeadBranch,
		&i.HeadSha,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrUpdateGithubFile = `-- name: CreateOrUpdateGithubFile :exec

INSERT INTO github_files (repo_owner, repo_name, path, content, sha, branch, session_id, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, unixepoch())
ON CONFLICT(repo_owner, repo_name, path, branch, session_id)
DO UPDATE SET content = excluded.content, sha = excluded.sha, updated_at = unixepoch()
`

type CreateOrUpdateGithubFileParams struct {
	RepoOwner string `json:"repo_owner"`
	RepoName  string `json:"repo_name"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Sha       string `json:"sha"`
	Branch    string `json:"branch"`
	SessionID string `json:"session_id"`
}

// File queries
func (q *Queries) CreateOrUpdateGithubFile(ctx context.Context, arg CreateOrUpdateGithubFileParams) error {
	_, err := q.db.ExecContext(ctx, createOrUpdateGithubFile,
		arg.RepoOwner,
		arg.RepoName,
		arg.Path,
		arg.Content,
		arg.Sha,
		arg.Branch,
		arg.SessionID,
	)
	return err
}

const deleteGithubSessionData = `-- name: DeleteGithubSessionData :exec

DELETE FROM github_repositories WHERE session_id = ?
`

// Cleanup queries
func (q *Queries) DeleteGithubSessionData(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteGithubSessionData, sessionID)
	return err
}

const getGithubBranch = `-- name: GetGithubBranch :one
SELECT id, repo_owner, repo_name, name, sha, created_at
FROM github_branches
WHERE repo_owner = ? AND repo_name = ? AND name = ? AND session_id = ?
`

type GetGithubBranchParams struct {
	RepoOwner string `json:"repo_owner"`
	RepoName  string `json:"repo_name"`
	Name      string `json:"name"`
	SessionID string `json:"session_id"`
}

type GetGithubBranchRow struct {
	ID        int64  `json:"id"`
	RepoOwner string `json:"repo_owner"`
	RepoName  string `json:"repo_name"`
	Name      string `json:"name"`
	Sha       string `json:"sha"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) GetGithubBranch(ctx context.Context, arg GetGithubBranchParams) (GetGithubBranchRow, error) {
	row := q.db.QueryRowContext(ctx, getGithubBranch,
		arg.RepoOwner,
		arg.RepoName,
		arg.Name,
		arg.SessionID,
	)
	var i GetGithubBranchRow
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.Name,
		&i.Sha,
		&i.CreatedAt,
	)
	return i, err
}

const getGithubFile = `-- name: GetGithubFile :one
SELECT id, repo_owner, repo_name, path, content, sha, branch, updated_at
FROM github_files
WHERE repo_owner = ? AND repo_name = ? AND path = ? AND branch = ? AND session_id = ?
`

type GetGithubFileParams struct {
	RepoOwner string `json:"repo_owner"`
	RepoName  string `json:"repo_name"`
	Path      string `json:"path"`
	Branch    string `json:"branch"`
	SessionID string `json:"session_id"`
}

type GetGithubFileRow struct {
	ID        int64  `json:"id"`
	RepoOwner string `json:"repo_owner"`
	RepoName  string `json:"repo_name"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Sha       string `json:"sha"`
	Branch    string `json:"branch"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) GetGithubFile(ctx context.Context, arg GetGithubFileParams) (GetGithubFileRow, error) {
	row := q.db.QueryRowContext(ctx, getGithubFile,
		arg.RepoOwner,
		arg.RepoName,
		arg.Path,
		arg.Branch,
		arg.SessionID,
	)
	var i GetGithubFileRow
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.Path,
		&i.Content,
		&i.Sha,
		&i.Branch,
		&i.UpdatedAt,
	)
	return i, err
}

const getGithubIssue = `-- name: GetGithubIssue :one
SELECT id, repo_owner, repo_name, number, title, body, state, created_at, updated_at
FROM github_issues
WHERE repo_owner = ? AND repo_name = ? AND number = ? AND session_id = ?
`

type GetGithubIssueParams struct {
	RepoOwner string `json:"repo_owner"`
	RepoName  string `json:"repo_name"`
	Number    int64  `json:"number"`
	SessionID string `json:"session_id"`
}

type GetGithubIssueRow struct {
	ID        int64          `json:"id"`
	RepoOwner string         `json:"repo_owner"`
	RepoName  string         `json:"repo_name"`
	Number    int64          `json:"number"`
	Title     string         `json:"title"`
	Body      sql.NullString `json:"body"`
	State     string         `json:"state"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

func (q *Queries) GetGithubIssue(ctx context.Context, arg GetGithubIssueParams) (GetGithubIssueRow, error) {
	row := q.db.QueryRowContext(ctx, getGithubIssue,
		arg.RepoOwner,
		arg.RepoName,
		arg.Number,
		arg.SessionID,
	)
	var i GetGithubIssueRow
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGithubPullRequest = `-- name: GetGithubPullRequest :one
SELECT id, repo_owner, repo_name, number, title, body, head, base, state, merged, created_at, updated_at
FROM github_pull_requests
WHERE repo_owner = ? AND repo_name = ? AND number = ? AND session_id = ?
`

type GetGithubPullRequestParams struct {
	RepoOwner string `json:"repo_owner"`
	RepoName  string `json:"repo_name"`
	Number    int64  `json:"number"`
	SessionID string `json:"session_id"`
}

type GetGithubPullRequestRow struct {
	ID        int64          `json:"id"`
	RepoOwner string         `json:"repo_owner"`
	RepoName  string         `json:"repo_name"`
	Number    int64          `json:"number"`
	Title     string         `json:"title"`
	Body      sql.NullString `json:"body"`
	Head      string         `json:"head"`
	Base      string         `json:"base"`
	State     string         `json:"state"`
	Merged    int64          `json:"merged"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

func (q *Queries) GetGithubPullRequest(ctx context.Context, arg GetGithubPullRequestParams) (GetGithubPullRequestRow, error) {
	row := q.db.QueryRowContext(ctx, getGithubPullRequest,
		arg.RepoOwner,
		arg.RepoName,
		arg.Number,
		arg.SessionID,
	)
	var i GetGithubPullRequestRow
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.Head,
		&i.Base,
		&i.State,
		&i.Merged,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGithubRepository = `-- name: GetGithubRepository :one
SELECT id, owner, name, default_branch, description, created_at
FROM github_repositories
WHERE owner = ? AND name = ? AND session_id = ?
`

type GetGithubRepositoryParams struct {
	Owner     string `json:"owner"`
	Name      string `json:"name"`
	SessionID string `json:"session_id"`
}

type GetGithubRepositoryRow struct {
	ID            int64          `json:"id"`
	Owner         string         `json:"owner"`
	Name          string         `json:"name"`
	DefaultBranch string         `json:"default_branch"`
	Description   sql.NullString `json:"description"`
	CreatedAt     int64          `json:"created_at"`
}

func (q *Queries) GetGithubRepository(ctx context.Context, arg GetGithubRepositoryParams) (GetGithubRepositoryRow, error) {
	row := q.db.QueryRowContext(ctx, getGithubRepository, arg.Owner, arg.Name, arg.SessionID)
	var i GetGithubRepositoryRow
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.DefaultBranch,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getGithubWorkflow = `-- name: GetGithubWorkflow :one
SELECT id, repo_owner, repo_name, workflow_id, name, path, state, created_at
FROM github_workflows
WHERE repo_owner = ? AND repo_name = ? AND workflow_id = ? AND session_id = ?
`

type GetGithubWorkflowParams struct {
	RepoOwner  string `json:"repo_owner"`
	RepoName   string `json:"repo_name"`
	WorkflowID int64  `json:"workflow_id"`
	SessionID  string `json:"session_id"`
}

type GetGithubWorkflowRow struct {
	ID         int64  `json:"id"`
	RepoOwner  string `json:"repo_owner"`
	RepoName   string `json:"repo_name"`
	WorkflowID int64  `json:"workflow_id"`
	Name       string `json:"name"`
	Path       string `json:"path"`
	State      string `json:"state"`
	CreatedAt  int64  `json:"created_at"`
}

func (q *Queries) GetGithubWorkflow(ctx context.Context, arg GetGithubWorkflowParams) (GetGithubWorkflowRow, error) {
	row := q.db.QueryRowContext(ctx, getGithubWorkflow,
		arg.RepoOwner,
		arg.RepoName,
		arg.WorkflowID,
		arg.SessionID,
	)
	var i GetGithubWorkflowRow
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.WorkflowID,
		&i.Name,
		&i.Path,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const getGithubWorkflowRun = `-- name: GetGithubWorkflowRun :one
SELECT id, repo_owner, repo_name, run_id, workflow_id, status, conclusion, head_branch, head_sha, created_at, updated_at
FROM github_workflow_runs
WHERE repo_owner = ? AND repo_name = ? AND run_id = ? AND session_id = ?
`

type GetGithubWorkflowRunParams struct {
	RepoOwner string `json:"repo_owner"`
	RepoName  string `json:"repo_name"`
	RunID     int64  `json:"run_id"`
	SessionID string `json:"session_id"`
}

type GetGithubWorkflowRunRow struct {
	ID         int64          `json:"id"`
	RepoOwner  string         `json:"repo_owner"`
	RepoName   string         `json:"repo_name"`
	RunID      int64          `json:"run_id"`
	WorkflowID int64          `json:"workflow_id"`
	Status     string         `json:"status"`
	Conclusion sql.NullString `json:"conclusion"`
	HeadBranch sql.NullString `json:"head_branch"`
	HeadSha    sql.NullString `json:"head_sha"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

func (q *Queries) GetGithubWorkflowRun(ctx context.Context, arg GetGithubWorkflowRunParams) (GetGithubWorkflowRunRow, error) {
	row := q.db.QueryRowContext(ctx, getGithubWorkflowRun,
		arg.RepoOwner,
		arg.RepoName,
		arg.RunID,
		arg.SessionID,
	)
	var i GetGithubWorkflowRunRow
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.RunID,
		&i.WorkflowID,
		&i.Status,
		&i.Conclusion,
		&i.HeadBranch,
		&i.HeadSha,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextCommentID = `-- name: GetNextCommentID :one
SELECT COALESCE(MAX(comment_id), 0) + 1 as next_id
FROM github_issue_comments
WHERE repo_owner = ? AND repo_name = ? AND session_id = ?
`

type GetNextCommentIDParams struct {
	RepoOwner string `json:"repo_owner"`
	RepoName  string `json:"repo_name"`
	SessionID string `json:"session_id"`
}

func (q *Queries) GetNextCommentID(ctx context.Context, arg GetNextCommentIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextCommentID, arg.RepoOwner, arg.RepoName, arg.SessionID)
	var next_id int64
	err := row.Scan(&next_id)
	return next_id, err
}

const getNextIssueNumber = `-- name: GetNextIssueNumber :one
SELECT COALESCE(MAX(number), 0) + 1 as next_number
FROM github_issues
WHERE repo_owner = ? AND repo_name = ? AND session_id = ?
`

type GetNextIssueNumberParams struct {
	RepoOwner string `json:"repo_owner"`
	RepoName  string `json:"repo_name"`
	SessionID string `json:"session_id"`
}

func (q *Queries) GetNextIssueNumber(ctx context.Context, arg GetNextIssueNumberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextIssueNumber, arg.RepoOwner, arg.RepoName, arg.SessionID)
	var next_number int64
	err := row.Scan(&next_number)
	return next_number, err
}

const getNextPRNumber = `-- name: GetNextPRNumber :one
SELECT COALESCE(MAX(number), 0) + 1 as next_number
FROM github_pull_requests
WHERE repo_owner = ? AND repo_name = ? AND session_id = ?
`

type GetNextPRNumberParams struct {
	RepoOwner string `json:"repo_owner"`
	RepoName  string `json:"repo_name"`
	SessionID string `json:"session_id"`
}

func (q *Queries) GetNextPRNumber(ctx context.Context, arg GetNextPRNumberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextPRNumber, arg.RepoOwner, arg.RepoName, arg.SessionID)
	var next_number int64
	err := row.Scan(&next_number)
	return next_number, err
}

const getNextWorkflowRunID = `-- name: GetNextWorkflowRunID :one
SELECT COALESCE(MAX(run_id), 0) + 1 as next_id
FROM github_workflow_runs
WHERE repo_owner = ? AND repo_name = ? AND session_id = ?
`

type GetNextWorkflowRunIDParams struct {
	RepoOwner string `json:"repo_owner"`
	RepoName  string `json:"repo_name"`
	SessionID string `json:"session_id"`
}

func (q *Queries) GetNextWorkflowRunID(ctx context.Context, arg GetNextWorkflowRunIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextWorkflowRunID, arg.RepoOwner, arg.RepoName, arg.SessionID)
	var next_id int64
	err := row.Scan(&next_id)
	return next_id, err
}

const listGithubIssueComments = `-- name: ListGithubIssueComments :many
SELECT id, repo_owner, repo_name, issue_number, comment_id, body, created_at
FROM github_issue_comments
WHERE repo_owner = ? AND repo_name = ? AND issue_number = ? AND session_id = ?
ORDER BY created_at ASC
`

type ListGithubIssueCommentsParams struct {
	RepoOwner   string `json:"repo_owner"`
	RepoName    string `json:"repo_name"`
	IssueNumber int64  `json:"issue_number"`
	SessionID   string `json:"session_id"`
}

type ListGithubIssueCommentsRow struct {
	ID          int64  `json:"id"`
	RepoOwner   string `json:"repo_owner"`
	RepoName    string `json:"repo_name"`
	IssueNumber int64  `json:"issue_number"`
	CommentID   int64  `json:"comment_id"`
	Body        string `json:"body"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) ListGithubIssueComments(ctx context.Context, arg ListGithubIssueCommentsParams) ([]ListGithubIssueCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGithubIssueComments,
		arg.RepoOwner,
		arg.RepoName,
		arg.IssueNumber,
		arg.SessionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGithubIssueCommentsRow{}
	for rows.Next() {
		var i ListGithubIssueCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoOwner,
			&i.RepoName,
			&i.IssueNumber,
			&i.CommentID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGithubIssues = `-- name: ListGithubIssues :many
SELECT id, repo_owner, repo_name, number, title, body, state, created_at, updated_at
FROM github_issues
WHERE repo_owner = ? AND repo_name = ? AND session_id = ?
  AND (?4 = '' OR state = ?4)
ORDER BY created_at DESC
`

type ListGithubIssuesParams struct {
	RepoOwner   string      `json:"repo_owner"`
	RepoName    string      `json:"repo_name"`
	SessionID   string      `json:"session_id"`
	StateFilter interface{} `json:"state_filter"`
}

type ListGithubIssuesRow struct {
	ID        int64          `json:"id"`
	RepoOwner string         `json:"repo_owner"`
	RepoName  string         `json:"repo_name"`
	Number    int64          `json:"number"`
	Title     string         `json:"title"`
	Body      sql.NullString `json:"body"`
	State     string         `json:"state"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

func (q *Queries) ListGithubIssues(ctx context.Context, arg ListGithubIssuesParams) ([]ListGithubIssuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGithubIssues,
		arg.RepoOwner,
		arg.RepoName,
		arg.SessionID,
		arg.StateFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGithubIssuesRow{}
	for rows.Next() {
		var i ListGithubIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoOwner,
			&i.RepoName,
			&i.Number,
			&i.Title,
			&i.Body,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGithubIssuesBySession = `-- name: ListGithubIssuesBySession :many
SELECT id, repo_owner, repo_name, number, title, body, state, created_at, updated_at
FROM github_issues
WHERE session_id = ?
ORDER BY created_at DESC
`

type ListGithubIssuesBySessionRow struct {
	ID        int64          `json:"id"`
	RepoOwner string         `json:"repo_owner"`
	RepoName  string         `json:"repo_name"`
	Number    int64          `json:"number"`
	Title     string         `json:"title"`
	Body      sql.NullString `json:"body"`
	State     string         `json:"state"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

// UI data queries
func (q *Queries) ListGithubIssuesBySession(ctx context.Context, sessionID string) ([]ListGithubIssuesBySessionRow, error) {
	rows, err := q.db.QueryContext(ctx, listGithubIssuesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGithubIssuesBySessionRow{}
	for rows.Next() {
		var i ListGithubIssuesBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoOwner,
			&i.RepoName,
			&i.Number,
			&i.Title,
			&i.Body,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGithubPullRequests = `-- name: ListGithubPullRequests :many
SELECT id, repo_owner, repo_name, number, title, body, head, base, state, merged, created_at, updated_at
FROM github_pull_requests
WHERE repo_owner = ? AND repo_name = ? AND session_id = ?
  AND (?4 = '' OR state = ?4)
ORDER BY created_at DESC
`

type ListGithubPullRequestsParams struct {
	RepoOwner   string      `json:"repo_owner"`
	RepoName    string      `json:"repo_name"`
	SessionID   string      `json:"session_id"`
	StateFilter interface{} `json:"state_filter"`
}

type ListGithubPullRequestsRow struct {
	ID        int64          `json:"id"`
	RepoOwner string         `json:"repo_owner"`
	RepoName  string         `json:"repo_name"`
	Number    int64          `json:"number"`
	Title     string         `json:"title"`
	Body      sql.NullString `json:"body"`
	Head      string         `json:"head"`
	Base      string         `json:"base"`
	State     string         `json:"state"`
	Merged    int64          `json:"merged"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

func (q *Queries) ListGithubPullRequests(ctx context.Context, arg ListGithubPullRequestsParams) ([]ListGithubPullRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGithubPullRequests,
		arg.RepoOwner,
		arg.RepoName,
		arg.SessionID,
		arg.StateFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGithubPullRequestsRow{}
	for rows.Next() {
		var i ListGithubPullRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoOwner,
			&i.RepoName,
			&i.Number,
			&i.Title,
			&i.Body,
			&i.Head,
			&i.Base,
			&i.State,
			&i.Merged,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGithubRepositories = `-- name: ListGithubRepositories :many
SELECT id, owner, name, default_branch, description, created_at
FROM github_repositories
WHERE session_id = ? AND owner = ?
ORDER BY created_at DESC
`

type ListGithubRepositoriesParams struct {
	SessionID string `json:"session_id"`
	Owner     string `json:"owner"`
}

type ListGithubRepositoriesRow struct {
	ID            int64          `json:"id"`
	Owner         string         `json:"owner"`
	Name          string         `json:"name"`
	DefaultBranch string         `json:"default_branch"`
	Description   sql.NullString `json:"description"`
	CreatedAt     int64          `json:"created_at"`
}

func (q *Queries) ListGithubRepositories(ctx context.Context, arg ListGithubRepositoriesParams) ([]ListGithubRepositoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGithubRepositories, arg.SessionID, arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGithubRepositoriesRow{}
	for rows.Next() {
		var i ListGithubRepositoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Name,
			&i.DefaultBranch,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGithubWorkflowRuns = `-- name: ListGithubWorkflowRuns :many
SELECT id, repo_owner, repo_name, run_id, workflow_id, status, conclusion, head_branch, head_sha, created_at, updated_at
FROM github_workflow_runs
WHERE repo_owner = ? AND repo_name = ? AND session_id = ?
ORDER BY created_at DESC
`

type ListGithubWorkflowRunsParams struct {
	RepoOwner string `json:"repo_owner"`
	RepoName  string `json:"repo_name"`
	SessionID string `json:"session_id"`
}

type ListGithubWorkflowRunsRow struct {
	ID         int64          `json:"id"`
	RepoOwner  string         `json:"repo_owner"`
	RepoName   string         `json:"repo_name"`
	RunID      int64          `json:"run_id"`
	WorkflowID int64          `json:"workflow_id"`
	Status     string         `json:"status"`
	Conclusion sql.NullString `json:"conclusion"`
	HeadBranch sql.NullString `json:"head_branch"`
	HeadSha    sql.NullString `json:"head_sha"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

func (q *Queries) ListGithubWorkflowRuns(ctx context.Context, arg ListGithubWorkflowRunsParams) ([]ListGithubWorkflowRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGithubWorkflowRuns, arg.RepoOwner, arg.RepoName, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGithubWorkflowRunsRow{}
	for rows.Next() {
		var i ListGithubWorkflowRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoOwner,
			&i.RepoName,
			&i.RunID,
			&i.WorkflowID,
			&i.Status,
			&i.Conclusion,
			&i.HeadBranch,
			&i.HeadSha,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGithubWorkflowRunsForWorkflow = `-- name: ListGithubWorkflowRunsForWorkflow :many
SELECT id, repo_owner, repo_name, run_id, workflow_id, status, conclusion, head_branch, head_sha, created_at, updated_at
FROM github_workflow_runs
WHERE repo_owner = ? AND repo_name = ? AND workflow_id = ? AND session_id = ?
ORDER BY created_at DESC
`

type ListGithubWorkflowRunsForWorkflowParams struct {
	RepoOwner  string `json:"repo_owner"`
	RepoName   string `json:"repo_name"`
	WorkflowID int64  `json:"workflow_id"`
	SessionID  string `json:"session_id"`
}

type ListGithubWorkflowRunsForWorkflowRow struct {
	ID         int64          `json:"id"`
	RepoOwner  string         `json:"repo_owner"`
	RepoName   string         `json:"repo_name"`
	RunID      int64          `json:"run_id"`
	WorkflowID int64          `json:"workflow_id"`
	Status     string         `json:"status"`
	Conclusion sql.NullString `json:"conclusion"`
	HeadBranch sql.NullString `json:"head_branch"`
	HeadSha    sql.NullString `json:"head_sha"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

func (q *Queries) ListGithubWorkflowRunsForWorkflow(ctx context.Context, arg ListGithubWorkflowRunsForWorkflowParams) ([]ListGithubWorkflowRunsForWorkflowRow, error) {
	rows, err := q.db.QueryContext(ctx, listGithubWorkflowRunsForWorkflow,
		arg.RepoOwner,
		arg.RepoName,
		arg.WorkflowID,
		arg.SessionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGithubWorkflowRunsForWorkflowRow{}
	for rows.Next() {
		var i ListGithubWorkflowRunsForWorkflowRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoOwner,
			&i.RepoName,
			&i.RunID,
			&i.WorkflowID,
			&i.Status,
			&i.Conclusion,
			&i.HeadBranch,
			&i.HeadSha,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGithubWorkflows = `-- name: ListGithubWorkflows :many
SELECT id, repo_owner, repo_name, workflow_id, name, path, state, created_at
FROM github_workflows
WHERE repo_owner = ? AND repo_name = ? AND session_id = ?
ORDER BY created_at DESC
`

type ListGithubWorkflowsParams struct {
	RepoOwner string `json:"repo_owner"`
	RepoName  string `json:"repo_name"`
	SessionID string `json:"session_id"`
}

type ListGithubWorkflowsRow struct {
	ID         int64  `json:"id"`
	RepoOwner  string `json:"repo_owner"`
	RepoName   string `json:"repo_name"`
	WorkflowID int64  `json:"workflow_id"`
	Name       string `json:"name"`
	Path       string `json:"path"`
	State      string `json:"state"`
	CreatedAt  int64  `json:"created_at"`
}

func (q *Queries) ListGithubWorkflows(ctx context.Context, arg ListGithubWorkflowsParams) ([]ListGithubWorkflowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGithubWorkflows, arg.RepoOwner, arg.RepoName, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGithubWorkflowsRow{}
	for rows.Next() {
		var i ListGithubWorkflowsRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoOwner,
			&i.RepoName,
			&i.WorkflowID,
			&i.Name,
			&i.Path,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeGithubPullRequest = `-- name: MergeGithubPullRequest :exec
UPDATE github_pull_requests
SET state = 'closed', merged = 1, updated_at = unixepoch()
WHERE repo_owner = ? AND repo_name = ? AND number = ? AND session_id = ?
`

type MergeGithubPullRequestParams struct {
	RepoOwner string `json:"repo_owner"`
	RepoName  string `json:"repo_name"`
	Number    int64  `json:"number"`
	SessionID string `json:"session_id"`
}

func (q *Queries) MergeGithubPullRequest(ctx context.Context, arg MergeGithubPullRequestParams) error {
	_, err := q.db.ExecContext(ctx, mergeGithubPullRequest,
		arg.RepoOwner,
		arg.RepoName,
		arg.Number,
		arg.SessionID,
	)
	return err
}

const updateGithubBranchSHA = `-- name: UpdateGithubBranchSHA :exec
UPDATE github_branches
SET sha = ?
WHERE repo_owner = ? AND repo_name = ? AND name = ? AND session_id = ?
`

type UpdateGithubBranchSHAParams struct {
	Sha       string `json:"sha"`
	RepoOwner string `json:"repo_owner"`
	RepoName  string `json:"repo_name"`
	Name      string `json:"name"`
	SessionID string `json:"session_id"`
}

func (q *Queries) UpdateGithubBranchSHA(ctx context.Context, arg UpdateGithubBranchSHAParams) error {
	_, err := q.db.ExecContext(ctx, updateGithubBranchSHA,
		arg.Sha,
		arg.RepoOwner,
		arg.RepoName,
		arg.Name,
		arg.SessionID,
	)
	return err
}

const updateGithubIssue = `-- name: UpdateGithubIssue :exec
UPDATE github_issues
SET title = ?, body = ?, state = ?, updated_at = unixepoch()
WHERE repo_owner = ? AND repo_name = ? AND number = ? AND session_id = ?
`

type UpdateGithubIssueParams struct {
	Title     string         `json:"title"`
	Body      sql.NullString `json:"body"`
	State     string         `json:"state"`
	RepoOwner string         `json:"repo_owner"`
	RepoName  string         `json:"repo_name"`
	Number    int64          `json:"number"`
	SessionID string         `json:"session_id"`
}

func (q *Queries) UpdateGithubIssue(ctx context.Context, arg UpdateGithubIssueParams) error {
	_, err := q.db.ExecContext(ctx, updateGithubIssue,
		arg.Title,
		arg.Body,
		arg.State,
		arg.RepoOwner,
		arg.RepoName,
		arg.Number,
		arg.SessionID,
	)
	return err
}
