// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gmail.sql

package database

import (
	"context"
	"database/sql"
)

const createGmailMessage = `-- name: CreateGmailMessage :exec
INSERT INTO gmail_messages (id, thread_id, from_email, to_email, subject, body_plain, body_html, raw_message, snippet, label_ids, internal_date, size_estimate, session_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateGmailMessageParams struct {
	ID           string         `json:"id"`
	ThreadID     string         `json:"thread_id"`
	FromEmail    string         `json:"from_email"`
	ToEmail      string         `json:"to_email"`
	Subject      string         `json:"subject"`
	BodyPlain    sql.NullString `json:"body_plain"`
	BodyHtml     sql.NullString `json:"body_html"`
	RawMessage   string         `json:"raw_message"`
	Snippet      sql.NullString `json:"snippet"`
	LabelIds     sql.NullString `json:"label_ids"`
	InternalDate int64          `json:"internal_date"`
	SizeEstimate int64          `json:"size_estimate"`
	SessionID    string         `json:"session_id"`
}

func (q *Queries) CreateGmailMessage(ctx context.Context, arg CreateGmailMessageParams) error {
	_, err := q.db.ExecContext(ctx, createGmailMessage,
		arg.ID,
		arg.ThreadID,
		arg.FromEmail,
		arg.ToEmail,
		arg.Subject,
		arg.BodyPlain,
		arg.BodyHtml,
		arg.RawMessage,
		arg.Snippet,
		arg.LabelIds,
		arg.InternalDate,
		arg.SizeEstimate,
		arg.SessionID,
	)
	return err
}

const deleteGmailSessionData = `-- name: DeleteGmailSessionData :exec
DELETE FROM gmail_messages WHERE session_id = ?
`

func (q *Queries) DeleteGmailSessionData(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteGmailSessionData, sessionID)
	return err
}

const getGmailMessageByID = `-- name: GetGmailMessageByID :one
SELECT id, thread_id, from_email, to_email, subject, body_plain, body_html, raw_message, snippet, label_ids, internal_date, size_estimate, created_at
FROM gmail_messages
WHERE id = ? AND session_id = ?
`

type GetGmailMessageByIDParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
}

type GetGmailMessageByIDRow struct {
	ID           string         `json:"id"`
	ThreadID     string         `json:"thread_id"`
	FromEmail    string         `json:"from_email"`
	ToEmail      string         `json:"to_email"`
	Subject      string         `json:"subject"`
	BodyPlain    sql.NullString `json:"body_plain"`
	BodyHtml     sql.NullString `json:"body_html"`
	RawMessage   string         `json:"raw_message"`
	Snippet      sql.NullString `json:"snippet"`
	LabelIds     sql.NullString `json:"label_ids"`
	InternalDate int64          `json:"internal_date"`
	SizeEstimate int64          `json:"size_estimate"`
	CreatedAt    int64          `json:"created_at"`
}

func (q *Queries) GetGmailMessageByID(ctx context.Context, arg GetGmailMessageByIDParams) (GetGmailMessageByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getGmailMessageByID, arg.ID, arg.SessionID)
	var i GetGmailMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.FromEmail,
		&i.ToEmail,
		&i.Subject,
		&i.BodyPlain,
		&i.BodyHtml,
		&i.RawMessage,
		&i.Snippet,
		&i.LabelIds,
		&i.InternalDate,
		&i.SizeEstimate,
		&i.CreatedAt,
	)
	return i, err
}

const listGmailMessages = `-- name: ListGmailMessages :many
SELECT id, thread_id, snippet, label_ids, internal_date
FROM gmail_messages
WHERE session_id = ?
ORDER BY internal_date DESC
LIMIT ?
`

type ListGmailMessagesParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
}

type ListGmailMessagesRow struct {
	ID           string         `json:"id"`
	ThreadID     string         `json:"thread_id"`
	Snippet      sql.NullString `json:"snippet"`
	LabelIds     sql.NullString `json:"label_ids"`
	InternalDate int64          `json:"internal_date"`
}

func (q *Queries) ListGmailMessages(ctx context.Context, arg ListGmailMessagesParams) ([]ListGmailMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGmailMessages, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGmailMessagesRow{}
	for rows.Next() {
		var i ListGmailMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Snippet,
			&i.LabelIds,
			&i.InternalDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchGmailMessages = `-- name: SearchGmailMessages :many
SELECT id, thread_id, from_email, to_email, subject, snippet, label_ids, internal_date
FROM gmail_messages
WHERE
    session_id = ?
    AND (? = '' OR from_email LIKE '%' || ? || '%')
    AND (? = '' OR to_email LIKE '%' || ? || '%')
    AND (? = '' OR subject LIKE '%' || ? || '%')
    AND (? = '' OR body_plain LIKE '%' || ? || '%')
ORDER BY internal_date DESC
LIMIT ?
`

type SearchGmailMessagesParams struct {
	SessionID string         `json:"session_id"`
	Column2   interface{}    `json:"column_2"`
	Column3   sql.NullString `json:"column_3"`
	Column4   interface{}    `json:"column_4"`
	Column5   sql.NullString `json:"column_5"`
	Column6   interface{}    `json:"column_6"`
	Column7   sql.NullString `json:"column_7"`
	Column8   interface{}    `json:"column_8"`
	Column9   sql.NullString `json:"column_9"`
	Limit     int64          `json:"limit"`
}

type SearchGmailMessagesRow struct {
	ID           string         `json:"id"`
	ThreadID     string         `json:"thread_id"`
	FromEmail    string         `json:"from_email"`
	ToEmail      string         `json:"to_email"`
	Subject      string         `json:"subject"`
	Snippet      sql.NullString `json:"snippet"`
	LabelIds     sql.NullString `json:"label_ids"`
	InternalDate int64          `json:"internal_date"`
}

func (q *Queries) SearchGmailMessages(ctx context.Context, arg SearchGmailMessagesParams) ([]SearchGmailMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchGmailMessages,
		arg.SessionID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchGmailMessagesRow{}
	for rows.Next() {
		var i SearchGmailMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.FromEmail,
			&i.ToEmail,
			&i.Subject,
			&i.Snippet,
			&i.LabelIds,
			&i.InternalDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
