// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gsheets.sql

package database

import (
	"context"
	"database/sql"
)

const clearRange = `-- name: ClearRange :exec
DELETE FROM gsheets_cells
WHERE spreadsheet_id = ? AND sheet_title = ?
  AND row >= ? AND row <= ?
  AND col >= ? AND col <= ?
  AND session_id = ?
`

type ClearRangeParams struct {
	SpreadsheetID string `json:"spreadsheet_id"`
	SheetTitle    string `json:"sheet_title"`
	Row           int64  `json:"row"`
	Row_2         int64  `json:"row_2"`
	Col           int64  `json:"col"`
	Col_2         int64  `json:"col_2"`
	SessionID     string `json:"session_id"`
}

func (q *Queries) ClearRange(ctx context.Context, arg ClearRangeParams) error {
	_, err := q.db.ExecContext(ctx, clearRange,
		arg.SpreadsheetID,
		arg.SheetTitle,
		arg.Row,
		arg.Row_2,
		arg.Col,
		arg.Col_2,
		arg.SessionID,
	)
	return err
}

const createSheet = `-- name: CreateSheet :exec
INSERT INTO gsheets_sheets (id, spreadsheet_id, title, sheet_id, session_id)
VALUES (?, ?, ?, ?, ?)
`

type CreateSheetParams struct {
	ID            string `json:"id"`
	SpreadsheetID string `json:"spreadsheet_id"`
	Title         string `json:"title"`
	SheetID       int64  `json:"sheet_id"`
	SessionID     string `json:"session_id"`
}

func (q *Queries) CreateSheet(ctx context.Context, arg CreateSheetParams) error {
	_, err := q.db.ExecContext(ctx, createSheet,
		arg.ID,
		arg.SpreadsheetID,
		arg.Title,
		arg.SheetID,
		arg.SessionID,
	)
	return err
}

const createSpreadsheet = `-- name: CreateSpreadsheet :exec
INSERT INTO gsheets_spreadsheets (id, title, session_id)
VALUES (?, ?, ?)
`

type CreateSpreadsheetParams struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	SessionID string `json:"session_id"`
}

func (q *Queries) CreateSpreadsheet(ctx context.Context, arg CreateSpreadsheetParams) error {
	_, err := q.db.ExecContext(ctx, createSpreadsheet, arg.ID, arg.Title, arg.SessionID)
	return err
}

const deleteGsheetsSessionData = `-- name: DeleteGsheetsSessionData :exec
DELETE FROM gsheets_spreadsheets WHERE session_id = ?
`

func (q *Queries) DeleteGsheetsSessionData(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteGsheetsSessionData, sessionID)
	return err
}

const deleteSheet = `-- name: DeleteSheet :exec
DELETE FROM gsheets_sheets
WHERE spreadsheet_id = ? AND sheet_id = ? AND session_id = ?
`

type DeleteSheetParams struct {
	SpreadsheetID string `json:"spreadsheet_id"`
	SheetID       int64  `json:"sheet_id"`
	SessionID     string `json:"session_id"`
}

func (q *Queries) DeleteSheet(ctx context.Context, arg DeleteSheetParams) error {
	_, err := q.db.ExecContext(ctx, deleteSheet, arg.SpreadsheetID, arg.SheetID, arg.SessionID)
	return err
}

const getCellValue = `-- name: GetCellValue :one
SELECT value
FROM gsheets_cells
WHERE spreadsheet_id = ? AND sheet_title = ? AND row = ? AND col = ? AND session_id = ?
`

type GetCellValueParams struct {
	SpreadsheetID string `json:"spreadsheet_id"`
	SheetTitle    string `json:"sheet_title"`
	Row           int64  `json:"row"`
	Col           int64  `json:"col"`
	SessionID     string `json:"session_id"`
}

func (q *Queries) GetCellValue(ctx context.Context, arg GetCellValueParams) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getCellValue,
		arg.SpreadsheetID,
		arg.SheetTitle,
		arg.Row,
		arg.Col,
		arg.SessionID,
	)
	var value sql.NullString
	err := row.Scan(&value)
	return value, err
}

const getCellsInRange = `-- name: GetCellsInRange :many
SELECT row, col, value
FROM gsheets_cells
WHERE spreadsheet_id = ? AND sheet_title = ?
  AND row >= ? AND row <= ?
  AND col >= ? AND col <= ?
  AND session_id = ?
ORDER BY row ASC, col ASC
`

type GetCellsInRangeParams struct {
	SpreadsheetID string `json:"spreadsheet_id"`
	SheetTitle    string `json:"sheet_title"`
	Row           int64  `json:"row"`
	Row_2         int64  `json:"row_2"`
	Col           int64  `json:"col"`
	Col_2         int64  `json:"col_2"`
	SessionID     string `json:"session_id"`
}

type GetCellsInRangeRow struct {
	Row   int64          `json:"row"`
	Col   int64          `json:"col"`
	Value sql.NullString `json:"value"`
}

func (q *Queries) GetCellsInRange(ctx context.Context, arg GetCellsInRangeParams) ([]GetCellsInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getCellsInRange,
		arg.SpreadsheetID,
		arg.SheetTitle,
		arg.Row,
		arg.Row_2,
		arg.Col,
		arg.Col_2,
		arg.SessionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCellsInRangeRow{}
	for rows.Next() {
		var i GetCellsInRangeRow
		if err := rows.Scan(&i.Row, &i.Col, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxRowInSheet = `-- name: GetMaxRowInSheet :one
SELECT COALESCE(MAX(row), 0) as max_row
FROM gsheets_cells
WHERE spreadsheet_id = ? AND sheet_title = ? AND session_id = ?
`

type GetMaxRowInSheetParams struct {
	SpreadsheetID string `json:"spreadsheet_id"`
	SheetTitle    string `json:"sheet_title"`
	SessionID     string `json:"session_id"`
}

func (q *Queries) GetMaxRowInSheet(ctx context.Context, arg GetMaxRowInSheetParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxRowInSheet, arg.SpreadsheetID, arg.SheetTitle, arg.SessionID)
	var max_row interface{}
	err := row.Scan(&max_row)
	return max_row, err
}

const getSheetByTitle = `-- name: GetSheetByTitle :one
SELECT id, spreadsheet_id, title, sheet_id
FROM gsheets_sheets
WHERE spreadsheet_id = ? AND title = ? AND session_id = ?
`

type GetSheetByTitleParams struct {
	SpreadsheetID string `json:"spreadsheet_id"`
	Title         string `json:"title"`
	SessionID     string `json:"session_id"`
}

type GetSheetByTitleRow struct {
	ID            string `json:"id"`
	SpreadsheetID string `json:"spreadsheet_id"`
	Title         string `json:"title"`
	SheetID       int64  `json:"sheet_id"`
}

func (q *Queries) GetSheetByTitle(ctx context.Context, arg GetSheetByTitleParams) (GetSheetByTitleRow, error) {
	row := q.db.QueryRowContext(ctx, getSheetByTitle, arg.SpreadsheetID, arg.Title, arg.SessionID)
	var i GetSheetByTitleRow
	err := row.Scan(
		&i.ID,
		&i.SpreadsheetID,
		&i.Title,
		&i.SheetID,
	)
	return i, err
}

const getSheetsBySpreadsheet = `-- name: GetSheetsBySpreadsheet :many
SELECT id, spreadsheet_id, title, sheet_id
FROM gsheets_sheets
WHERE spreadsheet_id = ? AND session_id = ?
ORDER BY created_at ASC
`

type GetSheetsBySpreadsheetParams struct {
	SpreadsheetID string `json:"spreadsheet_id"`
	SessionID     string `json:"session_id"`
}

type GetSheetsBySpreadsheetRow struct {
	ID            string `json:"id"`
	SpreadsheetID string `json:"spreadsheet_id"`
	Title         string `json:"title"`
	SheetID       int64  `json:"sheet_id"`
}

func (q *Queries) GetSheetsBySpreadsheet(ctx context.Context, arg GetSheetsBySpreadsheetParams) ([]GetSheetsBySpreadsheetRow, error) {
	rows, err := q.db.QueryContext(ctx, getSheetsBySpreadsheet, arg.SpreadsheetID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSheetsBySpreadsheetRow{}
	for rows.Next() {
		var i GetSheetsBySpreadsheetRow
		if err := rows.Scan(
			&i.ID,
			&i.SpreadsheetID,
			&i.Title,
			&i.SheetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpreadsheet = `-- name: GetSpreadsheet :one
SELECT id, title, created_at
FROM gsheets_spreadsheets
WHERE id = ? AND session_id = ?
`

type GetSpreadsheetParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
}

type GetSpreadsheetRow struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) GetSpreadsheet(ctx context.Context, arg GetSpreadsheetParams) (GetSpreadsheetRow, error) {
	row := q.db.QueryRowContext(ctx, getSpreadsheet, arg.ID, arg.SessionID)
	var i GetSpreadsheetRow
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const setCellValue = `-- name: SetCellValue :exec
INSERT INTO gsheets_cells (spreadsheet_id, sheet_title, row, col, value, session_id, updated_at)
VALUES (?, ?, ?, ?, ?, ?, unixepoch())
ON CONFLICT(spreadsheet_id, sheet_title, row, col, session_id)
DO UPDATE SET value = excluded.value, updated_at = unixepoch()
`

type SetCellValueParams struct {
	SpreadsheetID string         `json:"spreadsheet_id"`
	SheetTitle    string         `json:"sheet_title"`
	Row           int64          `json:"row"`
	Col           int64          `json:"col"`
	Value         sql.NullString `json:"value"`
	SessionID     string         `json:"session_id"`
}

func (q *Queries) SetCellValue(ctx context.Context, arg SetCellValueParams) error {
	_, err := q.db.ExecContext(ctx, setCellValue,
		arg.SpreadsheetID,
		arg.SheetTitle,
		arg.Row,
		arg.Col,
		arg.Value,
		arg.SessionID,
	)
	return err
}
