// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hubspot.sql

package database

import (
	"context"
	"database/sql"
)

const createHubspotAssociation = `-- name: CreateHubspotAssociation :exec
INSERT INTO hubspot_associations (from_object_type, from_object_id, to_object_type, to_object_id, association_type, session_id)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateHubspotAssociationParams struct {
	FromObjectType  string `json:"from_object_type"`
	FromObjectID    string `json:"from_object_id"`
	ToObjectType    string `json:"to_object_type"`
	ToObjectID      string `json:"to_object_id"`
	AssociationType string `json:"association_type"`
	SessionID       string `json:"session_id"`
}

// Associations queries
func (q *Queries) CreateHubspotAssociation(ctx context.Context, arg CreateHubspotAssociationParams) error {
	_, err := q.db.ExecContext(ctx, createHubspotAssociation,
		arg.FromObjectType,
		arg.FromObjectID,
		arg.ToObjectType,
		arg.ToObjectID,
		arg.AssociationType,
		arg.SessionID,
	)
	return err
}

const createHubspotCompany = `-- name: CreateHubspotCompany :one
INSERT INTO hubspot_companies (id, name, domain, city, industry, session_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, domain, city, industry, created_at, updated_at
`

type CreateHubspotCompanyParams struct {
	ID        string         `json:"id"`
	Name      sql.NullString `json:"name"`
	Domain    sql.NullString `json:"domain"`
	City      sql.NullString `json:"city"`
	Industry  sql.NullString `json:"industry"`
	SessionID string         `json:"session_id"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

type CreateHubspotCompanyRow struct {
	ID        string         `json:"id"`
	Name      sql.NullString `json:"name"`
	Domain    sql.NullString `json:"domain"`
	City      sql.NullString `json:"city"`
	Industry  sql.NullString `json:"industry"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

// Companies queries
func (q *Queries) CreateHubspotCompany(ctx context.Context, arg CreateHubspotCompanyParams) (CreateHubspotCompanyRow, error) {
	row := q.db.QueryRowContext(ctx, createHubspotCompany,
		arg.ID,
		arg.Name,
		arg.Domain,
		arg.City,
		arg.Industry,
		arg.SessionID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateHubspotCompanyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.City,
		&i.Industry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createHubspotContact = `-- name: CreateHubspotContact :one
INSERT INTO hubspot_contacts (id, email, first_name, last_name, mobile_phone, website, session_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, email, first_name, last_name, mobile_phone, website, created_at, updated_at
`

type CreateHubspotContactParams struct {
	ID          string         `json:"id"`
	Email       sql.NullString `json:"email"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	MobilePhone sql.NullString `json:"mobile_phone"`
	Website     sql.NullString `json:"website"`
	SessionID   string         `json:"session_id"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

type CreateHubspotContactRow struct {
	ID          string         `json:"id"`
	Email       sql.NullString `json:"email"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	MobilePhone sql.NullString `json:"mobile_phone"`
	Website     sql.NullString `json:"website"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

// Contacts queries
func (q *Queries) CreateHubspotContact(ctx context.Context, arg CreateHubspotContactParams) (CreateHubspotContactRow, error) {
	row := q.db.QueryRowContext(ctx, createHubspotContact,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.MobilePhone,
		arg.Website,
		arg.SessionID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateHubspotContactRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.MobilePhone,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createHubspotDeal = `-- name: CreateHubspotDeal :one
INSERT INTO hubspot_deals (id, deal_name, deal_stage, pipeline, amount, session_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, deal_name, deal_stage, pipeline, amount, created_at, updated_at
`

type CreateHubspotDealParams struct {
	ID        string         `json:"id"`
	DealName  sql.NullString `json:"deal_name"`
	DealStage sql.NullString `json:"deal_stage"`
	Pipeline  sql.NullString `json:"pipeline"`
	Amount    sql.NullString `json:"amount"`
	SessionID string         `json:"session_id"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

type CreateHubspotDealRow struct {
	ID        string         `json:"id"`
	DealName  sql.NullString `json:"deal_name"`
	DealStage sql.NullString `json:"deal_stage"`
	Pipeline  sql.NullString `json:"pipeline"`
	Amount    sql.NullString `json:"amount"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

// Deals queries
func (q *Queries) CreateHubspotDeal(ctx context.Context, arg CreateHubspotDealParams) (CreateHubspotDealRow, error) {
	row := q.db.QueryRowContext(ctx, createHubspotDeal,
		arg.ID,
		arg.DealName,
		arg.DealStage,
		arg.Pipeline,
		arg.Amount,
		arg.SessionID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateHubspotDealRow
	err := row.Scan(
		&i.ID,
		&i.DealName,
		&i.DealStage,
		&i.Pipeline,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHubspotSessionData = `-- name: DeleteHubspotSessionData :exec
DELETE FROM hubspot_associations WHERE session_id = ?
`

// Session management
func (q *Queries) DeleteHubspotSessionData(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteHubspotSessionData, sessionID)
	return err
}

const getHubspotAssociations = `-- name: GetHubspotAssociations :many
SELECT from_object_type, from_object_id, to_object_type, to_object_id, association_type, created_at
FROM hubspot_associations
WHERE from_object_type = ? AND from_object_id = ? AND session_id = ?
`

type GetHubspotAssociationsParams struct {
	FromObjectType string `json:"from_object_type"`
	FromObjectID   string `json:"from_object_id"`
	SessionID      string `json:"session_id"`
}

type GetHubspotAssociationsRow struct {
	FromObjectType  string `json:"from_object_type"`
	FromObjectID    string `json:"from_object_id"`
	ToObjectType    string `json:"to_object_type"`
	ToObjectID      string `json:"to_object_id"`
	AssociationType string `json:"association_type"`
	CreatedAt       int64  `json:"created_at"`
}

func (q *Queries) GetHubspotAssociations(ctx context.Context, arg GetHubspotAssociationsParams) ([]GetHubspotAssociationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getHubspotAssociations, arg.FromObjectType, arg.FromObjectID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHubspotAssociationsRow{}
	for rows.Next() {
		var i GetHubspotAssociationsRow
		if err := rows.Scan(
			&i.FromObjectType,
			&i.FromObjectID,
			&i.ToObjectType,
			&i.ToObjectID,
			&i.AssociationType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHubspotAssociationsByType = `-- name: GetHubspotAssociationsByType :many
SELECT from_object_type, from_object_id, to_object_type, to_object_id, association_type, created_at
FROM hubspot_associations
WHERE from_object_type = ? AND from_object_id = ? AND to_object_type = ? AND session_id = ?
`

type GetHubspotAssociationsByTypeParams struct {
	FromObjectType string `json:"from_object_type"`
	FromObjectID   string `json:"from_object_id"`
	ToObjectType   string `json:"to_object_type"`
	SessionID      string `json:"session_id"`
}

type GetHubspotAssociationsByTypeRow struct {
	FromObjectType  string `json:"from_object_type"`
	FromObjectID    string `json:"from_object_id"`
	ToObjectType    string `json:"to_object_type"`
	ToObjectID      string `json:"to_object_id"`
	AssociationType string `json:"association_type"`
	CreatedAt       int64  `json:"created_at"`
}

func (q *Queries) GetHubspotAssociationsByType(ctx context.Context, arg GetHubspotAssociationsByTypeParams) ([]GetHubspotAssociationsByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getHubspotAssociationsByType,
		arg.FromObjectType,
		arg.FromObjectID,
		arg.ToObjectType,
		arg.SessionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHubspotAssociationsByTypeRow{}
	for rows.Next() {
		var i GetHubspotAssociationsByTypeRow
		if err := rows.Scan(
			&i.FromObjectType,
			&i.FromObjectID,
			&i.ToObjectType,
			&i.ToObjectID,
			&i.AssociationType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHubspotCompanyByID = `-- name: GetHubspotCompanyByID :one
SELECT id, name, domain, city, industry, created_at, updated_at
FROM hubspot_companies
WHERE id = ? AND session_id = ?
`

type GetHubspotCompanyByIDParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
}

type GetHubspotCompanyByIDRow struct {
	ID        string         `json:"id"`
	Name      sql.NullString `json:"name"`
	Domain    sql.NullString `json:"domain"`
	City      sql.NullString `json:"city"`
	Industry  sql.NullString `json:"industry"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

func (q *Queries) GetHubspotCompanyByID(ctx context.Context, arg GetHubspotCompanyByIDParams) (GetHubspotCompanyByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getHubspotCompanyByID, arg.ID, arg.SessionID)
	var i GetHubspotCompanyByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.City,
		&i.Industry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHubspotContactByID = `-- name: GetHubspotContactByID :one
SELECT id, email, first_name, last_name, mobile_phone, website, created_at, updated_at
FROM hubspot_contacts
WHERE id = ? AND session_id = ?
`

type GetHubspotContactByIDParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
}

type GetHubspotContactByIDRow struct {
	ID          string         `json:"id"`
	Email       sql.NullString `json:"email"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	MobilePhone sql.NullString `json:"mobile_phone"`
	Website     sql.NullString `json:"website"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

func (q *Queries) GetHubspotContactByID(ctx context.Context, arg GetHubspotContactByIDParams) (GetHubspotContactByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getHubspotContactByID, arg.ID, arg.SessionID)
	var i GetHubspotContactByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.MobilePhone,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHubspotDealByID = `-- name: GetHubspotDealByID :one
SELECT id, deal_name, deal_stage, pipeline, amount, created_at, updated_at
FROM hubspot_deals
WHERE id = ? AND session_id = ?
`

type GetHubspotDealByIDParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
}

type GetHubspotDealByIDRow struct {
	ID        string         `json:"id"`
	DealName  sql.NullString `json:"deal_name"`
	DealStage sql.NullString `json:"deal_stage"`
	Pipeline  sql.NullString `json:"pipeline"`
	Amount    sql.NullString `json:"amount"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

func (q *Queries) GetHubspotDealByID(ctx context.Context, arg GetHubspotDealByIDParams) (GetHubspotDealByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getHubspotDealByID, arg.ID, arg.SessionID)
	var i GetHubspotDealByIDRow
	err := row.Scan(
		&i.ID,
		&i.DealName,
		&i.DealStage,
		&i.Pipeline,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHubspotCompanies = `-- name: ListHubspotCompanies :many
SELECT id, name, domain, city, industry, created_at, updated_at
FROM hubspot_companies
WHERE session_id = ?
ORDER BY created_at DESC
`

type ListHubspotCompaniesRow struct {
	ID        string         `json:"id"`
	Name      sql.NullString `json:"name"`
	Domain    sql.NullString `json:"domain"`
	City      sql.NullString `json:"city"`
	Industry  sql.NullString `json:"industry"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

func (q *Queries) ListHubspotCompanies(ctx context.Context, sessionID string) ([]ListHubspotCompaniesRow, error) {
	rows, err := q.db.QueryContext(ctx, listHubspotCompanies, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHubspotCompaniesRow{}
	for rows.Next() {
		var i ListHubspotCompaniesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.City,
			&i.Industry,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHubspotContacts = `-- name: ListHubspotContacts :many
SELECT id, email, first_name, last_name, mobile_phone, website, created_at, updated_at
FROM hubspot_contacts
WHERE session_id = ?
ORDER BY created_at DESC
`

type ListHubspotContactsRow struct {
	ID          string         `json:"id"`
	Email       sql.NullString `json:"email"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	MobilePhone sql.NullString `json:"mobile_phone"`
	Website     sql.NullString `json:"website"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

func (q *Queries) ListHubspotContacts(ctx context.Context, sessionID string) ([]ListHubspotContactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listHubspotContacts, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHubspotContactsRow{}
	for rows.Next() {
		var i ListHubspotContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.MobilePhone,
			&i.Website,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHubspotContactsBySession = `-- name: ListHubspotContactsBySession :many
SELECT id, email, first_name, last_name, mobile_phone, website, created_at, updated_at
FROM hubspot_contacts
WHERE session_id = ?
ORDER BY created_at DESC
`

type ListHubspotContactsBySessionRow struct {
	ID          string         `json:"id"`
	Email       sql.NullString `json:"email"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	MobilePhone sql.NullString `json:"mobile_phone"`
	Website     sql.NullString `json:"website"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

// UI data queries
func (q *Queries) ListHubspotContactsBySession(ctx context.Context, sessionID string) ([]ListHubspotContactsBySessionRow, error) {
	rows, err := q.db.QueryContext(ctx, listHubspotContactsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHubspotContactsBySessionRow{}
	for rows.Next() {
		var i ListHubspotContactsBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.MobilePhone,
			&i.Website,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHubspotDeals = `-- name: ListHubspotDeals :many
SELECT id, deal_name, deal_stage, pipeline, amount, created_at, updated_at
FROM hubspot_deals
WHERE session_id = ?
ORDER BY created_at DESC
`

type ListHubspotDealsRow struct {
	ID        string         `json:"id"`
	DealName  sql.NullString `json:"deal_name"`
	DealStage sql.NullString `json:"deal_stage"`
	Pipeline  sql.NullString `json:"pipeline"`
	Amount    sql.NullString `json:"amount"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

func (q *Queries) ListHubspotDeals(ctx context.Context, sessionID string) ([]ListHubspotDealsRow, error) {
	rows, err := q.db.QueryContext(ctx, listHubspotDeals, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHubspotDealsRow{}
	for rows.Next() {
		var i ListHubspotDealsRow
		if err := rows.Scan(
			&i.ID,
			&i.DealName,
			&i.DealStage,
			&i.Pipeline,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchHubspotContactsByEmail = `-- name: SearchHubspotContactsByEmail :many
SELECT id, email, first_name, last_name, mobile_phone, website, created_at, updated_at
FROM hubspot_contacts
WHERE email = ? AND session_id = ?
`

type SearchHubspotContactsByEmailParams struct {
	Email     sql.NullString `json:"email"`
	SessionID string         `json:"session_id"`
}

type SearchHubspotContactsByEmailRow struct {
	ID          string         `json:"id"`
	Email       sql.NullString `json:"email"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	MobilePhone sql.NullString `json:"mobile_phone"`
	Website     sql.NullString `json:"website"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

func (q *Queries) SearchHubspotContactsByEmail(ctx context.Context, arg SearchHubspotContactsByEmailParams) ([]SearchHubspotContactsByEmailRow, error) {
	rows, err := q.db.QueryContext(ctx, searchHubspotContactsByEmail, arg.Email, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchHubspotContactsByEmailRow{}
	for rows.Next() {
		var i SearchHubspotContactsByEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.MobilePhone,
			&i.Website,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHubspotCompany = `-- name: UpdateHubspotCompany :exec
UPDATE hubspot_companies
SET name = COALESCE(?, name),
    domain = COALESCE(?, domain),
    city = COALESCE(?, city),
    industry = COALESCE(?, industry),
    updated_at = ?
WHERE id = ? AND session_id = ?
`

type UpdateHubspotCompanyParams struct {
	Name      sql.NullString `json:"name"`
	Domain    sql.NullString `json:"domain"`
	City      sql.NullString `json:"city"`
	Industry  sql.NullString `json:"industry"`
	UpdatedAt int64          `json:"updated_at"`
	ID        string         `json:"id"`
	SessionID string         `json:"session_id"`
}

func (q *Queries) UpdateHubspotCompany(ctx context.Context, arg UpdateHubspotCompanyParams) error {
	_, err := q.db.ExecContext(ctx, updateHubspotCompany,
		arg.Name,
		arg.Domain,
		arg.City,
		arg.Industry,
		arg.UpdatedAt,
		arg.ID,
		arg.SessionID,
	)
	return err
}

const updateHubspotContact = `-- name: UpdateHubspotContact :exec
UPDATE hubspot_contacts
SET email = COALESCE(?, email),
    first_name = COALESCE(?, first_name),
    last_name = COALESCE(?, last_name),
    mobile_phone = COALESCE(?, mobile_phone),
    updated_at = ?
WHERE id = ? AND session_id = ?
`

type UpdateHubspotContactParams struct {
	Email       sql.NullString `json:"email"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	MobilePhone sql.NullString `json:"mobile_phone"`
	UpdatedAt   int64          `json:"updated_at"`
	ID          string         `json:"id"`
	SessionID   string         `json:"session_id"`
}

func (q *Queries) UpdateHubspotContact(ctx context.Context, arg UpdateHubspotContactParams) error {
	_, err := q.db.ExecContext(ctx, updateHubspotContact,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.MobilePhone,
		arg.UpdatedAt,
		arg.ID,
		arg.SessionID,
	)
	return err
}

const updateHubspotDeal = `-- name: UpdateHubspotDeal :exec
UPDATE hubspot_deals
SET deal_name = COALESCE(?, deal_name),
    deal_stage = COALESCE(?, deal_stage),
    amount = COALESCE(?, amount),
    updated_at = ?
WHERE id = ? AND session_id = ?
`

type UpdateHubspotDealParams struct {
	DealName  sql.NullString `json:"deal_name"`
	DealStage sql.NullString `json:"deal_stage"`
	Amount    sql.NullString `json:"amount"`
	UpdatedAt int64          `json:"updated_at"`
	ID        string         `json:"id"`
	SessionID string         `json:"session_id"`
}

func (q *Queries) UpdateHubspotDeal(ctx context.Context, arg UpdateHubspotDealParams) error {
	_, err := q.db.ExecContext(ctx, updateHubspotDeal,
		arg.DealName,
		arg.DealStage,
		arg.Amount,
		arg.UpdatedAt,
		arg.ID,
		arg.SessionID,
	)
	return err
}
