// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jira.sql

package database

import (
	"context"
	"database/sql"
)

const createJiraComment = `-- name: CreateJiraComment :exec
INSERT INTO jira_comments (id, issue_key, body, session_id)
VALUES (?, ?, ?, ?)
`

type CreateJiraCommentParams struct {
	ID        string `json:"id"`
	IssueKey  string `json:"issue_key"`
	Body      string `json:"body"`
	SessionID string `json:"session_id"`
}

func (q *Queries) CreateJiraComment(ctx context.Context, arg CreateJiraCommentParams) error {
	_, err := q.db.ExecContext(ctx, createJiraComment,
		arg.ID,
		arg.IssueKey,
		arg.Body,
		arg.SessionID,
	)
	return err
}

const createJiraIssue = `-- name: CreateJiraIssue :exec
INSERT INTO jira_issues (id, key, project_key, issue_type, summary, description, assignee, status, session_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateJiraIssueParams struct {
	ID          string         `json:"id"`
	Key         string         `json:"key"`
	ProjectKey  string         `json:"project_key"`
	IssueType   string         `json:"issue_type"`
	Summary     string         `json:"summary"`
	Description sql.NullString `json:"description"`
	Assignee    sql.NullString `json:"assignee"`
	Status      string         `json:"status"`
	SessionID   string         `json:"session_id"`
}

func (q *Queries) CreateJiraIssue(ctx context.Context, arg CreateJiraIssueParams) error {
	_, err := q.db.ExecContext(ctx, createJiraIssue,
		arg.ID,
		arg.Key,
		arg.ProjectKey,
		arg.IssueType,
		arg.Summary,
		arg.Description,
		arg.Assignee,
		arg.Status,
		arg.SessionID,
	)
	return err
}

const createJiraProject = `-- name: CreateJiraProject :exec
INSERT INTO jira_projects (id, key, name, session_id)
VALUES (?, ?, ?, ?)
`

type CreateJiraProjectParams struct {
	ID        string `json:"id"`
	Key       string `json:"key"`
	Name      string `json:"name"`
	SessionID string `json:"session_id"`
}

func (q *Queries) CreateJiraProject(ctx context.Context, arg CreateJiraProjectParams) error {
	_, err := q.db.ExecContext(ctx, createJiraProject,
		arg.ID,
		arg.Key,
		arg.Name,
		arg.SessionID,
	)
	return err
}

const createJiraTransition = `-- name: CreateJiraTransition :exec
INSERT INTO jira_transitions (id, name, to_status, session_id)
VALUES (?, ?, ?, ?)
`

type CreateJiraTransitionParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	ToStatus  string `json:"to_status"`
	SessionID string `json:"session_id"`
}

func (q *Queries) CreateJiraTransition(ctx context.Context, arg CreateJiraTransitionParams) error {
	_, err := q.db.ExecContext(ctx, createJiraTransition,
		arg.ID,
		arg.Name,
		arg.ToStatus,
		arg.SessionID,
	)
	return err
}

const deleteJiraSessionData = `-- name: DeleteJiraSessionData :exec
DELETE FROM jira_projects WHERE session_id = ?
`

func (q *Queries) DeleteJiraSessionData(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteJiraSessionData, sessionID)
	return err
}

const getJiraIssueByKey = `-- name: GetJiraIssueByKey :one
SELECT id, key, project_key, issue_type, summary, description, assignee, status, created_at, updated_at
FROM jira_issues
WHERE key = ? AND session_id = ?
`

type GetJiraIssueByKeyParams struct {
	Key       string `json:"key"`
	SessionID string `json:"session_id"`
}

type GetJiraIssueByKeyRow struct {
	ID          string         `json:"id"`
	Key         string         `json:"key"`
	ProjectKey  string         `json:"project_key"`
	IssueType   string         `json:"issue_type"`
	Summary     string         `json:"summary"`
	Description sql.NullString `json:"description"`
	Assignee    sql.NullString `json:"assignee"`
	Status      string         `json:"status"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

func (q *Queries) GetJiraIssueByKey(ctx context.Context, arg GetJiraIssueByKeyParams) (GetJiraIssueByKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getJiraIssueByKey, arg.Key, arg.SessionID)
	var i GetJiraIssueByKeyRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ProjectKey,
		&i.IssueType,
		&i.Summary,
		&i.Description,
		&i.Assignee,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJiraProjectByKey = `-- name: GetJiraProjectByKey :one
SELECT id, key, name, created_at
FROM jira_projects
WHERE key = ? AND session_id = ?
`

type GetJiraProjectByKeyParams struct {
	Key       string `json:"key"`
	SessionID string `json:"session_id"`
}

type GetJiraProjectByKeyRow struct {
	ID        string `json:"id"`
	Key       string `json:"key"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) GetJiraProjectByKey(ctx context.Context, arg GetJiraProjectByKeyParams) (GetJiraProjectByKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getJiraProjectByKey, arg.Key, arg.SessionID)
	var i GetJiraProjectByKeyRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getJiraTransitionByName = `-- name: GetJiraTransitionByName :one
SELECT id, name, to_status, created_at
FROM jira_transitions
WHERE name = ? AND session_id = ?
`

type GetJiraTransitionByNameParams struct {
	Name      string `json:"name"`
	SessionID string `json:"session_id"`
}

type GetJiraTransitionByNameRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	ToStatus  string `json:"to_status"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) GetJiraTransitionByName(ctx context.Context, arg GetJiraTransitionByNameParams) (GetJiraTransitionByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getJiraTransitionByName, arg.Name, arg.SessionID)
	var i GetJiraTransitionByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ToStatus,
		&i.CreatedAt,
	)
	return i, err
}

const listJiraComments = `-- name: ListJiraComments :many
SELECT id, issue_key, body, created_at
FROM jira_comments
WHERE issue_key = ? AND session_id = ?
ORDER BY created_at ASC
`

type ListJiraCommentsParams struct {
	IssueKey  string `json:"issue_key"`
	SessionID string `json:"session_id"`
}

type ListJiraCommentsRow struct {
	ID        string `json:"id"`
	IssueKey  string `json:"issue_key"`
	Body      string `json:"body"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) ListJiraComments(ctx context.Context, arg ListJiraCommentsParams) ([]ListJiraCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listJiraComments, arg.IssueKey, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJiraCommentsRow{}
	for rows.Next() {
		var i ListJiraCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueKey,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJiraIssuesBySession = `-- name: ListJiraIssuesBySession :many
SELECT id, key, project_key, issue_type, summary, description, assignee, status, created_at, updated_at
FROM jira_issues
WHERE session_id = ?
ORDER BY created_at DESC
`

type ListJiraIssuesBySessionRow struct {
	ID          string         `json:"id"`
	Key         string         `json:"key"`
	ProjectKey  string         `json:"project_key"`
	IssueType   string         `json:"issue_type"`
	Summary     string         `json:"summary"`
	Description sql.NullString `json:"description"`
	Assignee    sql.NullString `json:"assignee"`
	Status      string         `json:"status"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

// UI data queries
func (q *Queries) ListJiraIssuesBySession(ctx context.Context, sessionID string) ([]ListJiraIssuesBySessionRow, error) {
	rows, err := q.db.QueryContext(ctx, listJiraIssuesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJiraIssuesBySessionRow{}
	for rows.Next() {
		var i ListJiraIssuesBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.ProjectKey,
			&i.IssueType,
			&i.Summary,
			&i.Description,
			&i.Assignee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJiraProjects = `-- name: ListJiraProjects :many
SELECT id, key, name, created_at
FROM jira_projects
WHERE session_id = ?
ORDER BY created_at DESC
`

type ListJiraProjectsRow struct {
	ID        string `json:"id"`
	Key       string `json:"key"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) ListJiraProjects(ctx context.Context, sessionID string) ([]ListJiraProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listJiraProjects, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJiraProjectsRow{}
	for rows.Next() {
		var i ListJiraProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJiraTransitions = `-- name: ListJiraTransitions :many
SELECT id, name, to_status, created_at
FROM jira_transitions
WHERE session_id = ?
ORDER BY created_at ASC
`

type ListJiraTransitionsRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	ToStatus  string `json:"to_status"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) ListJiraTransitions(ctx context.Context, sessionID string) ([]ListJiraTransitionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listJiraTransitions, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJiraTransitionsRow{}
	for rows.Next() {
		var i ListJiraTransitionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ToStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchJiraIssues = `-- name: SearchJiraIssues :many
SELECT id, key, project_key, issue_type, summary, description, assignee, status, created_at, updated_at
FROM jira_issues
WHERE session_id = ?
    AND (? = '' OR project_key = ?)
    AND (? = '' OR issue_type = ?)
    AND (? = '' OR summary LIKE '%' || ? || '%')
    AND (? = '' OR assignee = ?)
    AND (? = '' OR status = ?)
ORDER BY created_at DESC
LIMIT ?
`

type SearchJiraIssuesParams struct {
	SessionID  string         `json:"session_id"`
	Column2    interface{}    `json:"column_2"`
	ProjectKey string         `json:"project_key"`
	Column4    interface{}    `json:"column_4"`
	IssueType  string         `json:"issue_type"`
	Column6    interface{}    `json:"column_6"`
	Column7    sql.NullString `json:"column_7"`
	Column8    interface{}    `json:"column_8"`
	Assignee   sql.NullString `json:"assignee"`
	Column10   interface{}    `json:"column_10"`
	Status     string         `json:"status"`
	Limit      int64          `json:"limit"`
}

type SearchJiraIssuesRow struct {
	ID          string         `json:"id"`
	Key         string         `json:"key"`
	ProjectKey  string         `json:"project_key"`
	IssueType   string         `json:"issue_type"`
	Summary     string         `json:"summary"`
	Description sql.NullString `json:"description"`
	Assignee    sql.NullString `json:"assignee"`
	Status      string         `json:"status"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

func (q *Queries) SearchJiraIssues(ctx context.Context, arg SearchJiraIssuesParams) ([]SearchJiraIssuesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchJiraIssues,
		arg.SessionID,
		arg.Column2,
		arg.ProjectKey,
		arg.Column4,
		arg.IssueType,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Assignee,
		arg.Column10,
		arg.Status,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchJiraIssuesRow{}
	for rows.Next() {
		var i SearchJiraIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.ProjectKey,
			&i.IssueType,
			&i.Summary,
			&i.Description,
			&i.Assignee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJiraIssue = `-- name: UpdateJiraIssue :exec
UPDATE jira_issues
SET summary = ?, description = ?, assignee = ?, updated_at = unixepoch()
WHERE key = ? AND session_id = ?
`

type UpdateJiraIssueParams struct {
	Summary     string         `json:"summary"`
	Description sql.NullString `json:"description"`
	Assignee    sql.NullString `json:"assignee"`
	Key         string         `json:"key"`
	SessionID   string         `json:"session_id"`
}

func (q *Queries) UpdateJiraIssue(ctx context.Context, arg UpdateJiraIssueParams) error {
	_, err := q.db.ExecContext(ctx, updateJiraIssue,
		arg.Summary,
		arg.Description,
		arg.Assignee,
		arg.Key,
		arg.SessionID,
	)
	return err
}

const updateJiraIssueStatus = `-- name: UpdateJiraIssueStatus :exec
UPDATE jira_issues
SET status = ?, updated_at = unixepoch()
WHERE key = ? AND session_id = ?
`

type UpdateJiraIssueStatusParams struct {
	Status    string `json:"status"`
	Key       string `json:"key"`
	SessionID string `json:"session_id"`
}

func (q *Queries) UpdateJiraIssueStatus(ctx context.Context, arg UpdateJiraIssueStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateJiraIssueStatus, arg.Status, arg.Key, arg.SessionID)
	return err
}
