// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: linear.sql

package database

import (
	"context"
	"database/sql"
)

const createLinearIssue = `-- name: CreateLinearIssue :one
INSERT INTO linear_issues (id, team_id, title, description, assignee_id, state_id, url, session_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, team_id, title, description, assignee_id, state_id, url, created_at, updated_at, archived_at
`

type CreateLinearIssueParams struct {
	ID          string         `json:"id"`
	TeamID      string         `json:"team_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	AssigneeID  sql.NullString `json:"assignee_id"`
	StateID     sql.NullString `json:"state_id"`
	Url         string         `json:"url"`
	SessionID   string         `json:"session_id"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

type CreateLinearIssueRow struct {
	ID          string         `json:"id"`
	TeamID      string         `json:"team_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	AssigneeID  sql.NullString `json:"assignee_id"`
	StateID     sql.NullString `json:"state_id"`
	Url         string         `json:"url"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
	ArchivedAt  sql.NullInt64  `json:"archived_at"`
}

// Issues queries
func (q *Queries) CreateLinearIssue(ctx context.Context, arg CreateLinearIssueParams) (CreateLinearIssueRow, error) {
	row := q.db.QueryRowContext(ctx, createLinearIssue,
		arg.ID,
		arg.TeamID,
		arg.Title,
		arg.Description,
		arg.AssigneeID,
		arg.StateID,
		arg.Url,
		arg.SessionID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateLinearIssueRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Title,
		&i.Description,
		&i.AssigneeID,
		&i.StateID,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createLinearState = `-- name: CreateLinearState :exec
INSERT INTO linear_states (id, name, type, team_id, session_id)
VALUES (?, ?, ?, ?, ?)
`

type CreateLinearStateParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	TeamID    string `json:"team_id"`
	SessionID string `json:"session_id"`
}

// States queries
func (q *Queries) CreateLinearState(ctx context.Context, arg CreateLinearStateParams) error {
	_, err := q.db.ExecContext(ctx, createLinearState,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.TeamID,
		arg.SessionID,
	)
	return err
}

const createLinearTeam = `-- name: CreateLinearTeam :exec
INSERT INTO linear_teams (id, name, key, session_id)
VALUES (?, ?, ?, ?)
`

type CreateLinearTeamParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Key       string `json:"key"`
	SessionID string `json:"session_id"`
}

// Teams queries
func (q *Queries) CreateLinearTeam(ctx context.Context, arg CreateLinearTeamParams) error {
	_, err := q.db.ExecContext(ctx, createLinearTeam,
		arg.ID,
		arg.Name,
		arg.Key,
		arg.SessionID,
	)
	return err
}

const createLinearUser = `-- name: CreateLinearUser :exec
INSERT INTO linear_users (id, name, email, session_id)
VALUES (?, ?, ?, ?)
`

type CreateLinearUserParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	SessionID string `json:"session_id"`
}

// Users queries
func (q *Queries) CreateLinearUser(ctx context.Context, arg CreateLinearUserParams) error {
	_, err := q.db.ExecContext(ctx, createLinearUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.SessionID,
	)
	return err
}

const deleteLinearSessionData = `-- name: DeleteLinearSessionData :exec
DELETE FROM linear_issues WHERE session_id = ?
`

// Session management
func (q *Queries) DeleteLinearSessionData(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteLinearSessionData, sessionID)
	return err
}

const getLinearIssueByID = `-- name: GetLinearIssueByID :one
SELECT id, team_id, title, description, assignee_id, state_id, url, created_at, updated_at, archived_at
FROM linear_issues
WHERE id = ? AND session_id = ?
`

type GetLinearIssueByIDParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
}

type GetLinearIssueByIDRow struct {
	ID          string         `json:"id"`
	TeamID      string         `json:"team_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	AssigneeID  sql.NullString `json:"assignee_id"`
	StateID     sql.NullString `json:"state_id"`
	Url         string         `json:"url"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
	ArchivedAt  sql.NullInt64  `json:"archived_at"`
}

func (q *Queries) GetLinearIssueByID(ctx context.Context, arg GetLinearIssueByIDParams) (GetLinearIssueByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLinearIssueByID, arg.ID, arg.SessionID)
	var i GetLinearIssueByIDRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Title,
		&i.Description,
		&i.AssigneeID,
		&i.StateID,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getLinearStateByID = `-- name: GetLinearStateByID :one
SELECT id, name, type, team_id, created_at
FROM linear_states
WHERE id = ? AND session_id = ?
`

type GetLinearStateByIDParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
}

type GetLinearStateByIDRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	TeamID    string `json:"team_id"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) GetLinearStateByID(ctx context.Context, arg GetLinearStateByIDParams) (GetLinearStateByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLinearStateByID, arg.ID, arg.SessionID)
	var i GetLinearStateByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.TeamID,
		&i.CreatedAt,
	)
	return i, err
}

const getLinearTeamByID = `-- name: GetLinearTeamByID :one
SELECT id, name, key, created_at
FROM linear_teams
WHERE id = ? AND session_id = ?
`

type GetLinearTeamByIDParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
}

type GetLinearTeamByIDRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Key       string `json:"key"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) GetLinearTeamByID(ctx context.Context, arg GetLinearTeamByIDParams) (GetLinearTeamByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLinearTeamByID, arg.ID, arg.SessionID)
	var i GetLinearTeamByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Key,
		&i.CreatedAt,
	)
	return i, err
}

const getLinearUserByID = `-- name: GetLinearUserByID :one
SELECT id, name, email, created_at
FROM linear_users
WHERE id = ? AND session_id = ?
`

type GetLinearUserByIDParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
}

type GetLinearUserByIDRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) GetLinearUserByID(ctx context.Context, arg GetLinearUserByIDParams) (GetLinearUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLinearUserByID, arg.ID, arg.SessionID)
	var i GetLinearUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const listLinearIssues = `-- name: ListLinearIssues :many
SELECT id, team_id, title, description, assignee_id, state_id, url, created_at, updated_at, archived_at
FROM linear_issues
WHERE session_id = ?
ORDER BY created_at DESC
`

type ListLinearIssuesRow struct {
	ID          string         `json:"id"`
	TeamID      string         `json:"team_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	AssigneeID  sql.NullString `json:"assignee_id"`
	StateID     sql.NullString `json:"state_id"`
	Url         string         `json:"url"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
	ArchivedAt  sql.NullInt64  `json:"archived_at"`
}

func (q *Queries) ListLinearIssues(ctx context.Context, sessionID string) ([]ListLinearIssuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLinearIssues, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinearIssuesRow{}
	for rows.Next() {
		var i ListLinearIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Title,
			&i.Description,
			&i.AssigneeID,
			&i.StateID,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinearIssuesBySession = `-- name: ListLinearIssuesBySession :many
SELECT id, team_id, title, description, assignee_id, state_id, url, created_at, updated_at, archived_at
FROM linear_issues
WHERE session_id = ?
ORDER BY created_at DESC
`

type ListLinearIssuesBySessionRow struct {
	ID          string         `json:"id"`
	TeamID      string         `json:"team_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	AssigneeID  sql.NullString `json:"assignee_id"`
	StateID     sql.NullString `json:"state_id"`
	Url         string         `json:"url"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
	ArchivedAt  sql.NullInt64  `json:"archived_at"`
}

// UI data queries
func (q *Queries) ListLinearIssuesBySession(ctx context.Context, sessionID string) ([]ListLinearIssuesBySessionRow, error) {
	rows, err := q.db.QueryContext(ctx, listLinearIssuesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinearIssuesBySessionRow{}
	for rows.Next() {
		var i ListLinearIssuesBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Title,
			&i.Description,
			&i.AssigneeID,
			&i.StateID,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinearIssuesByTeam = `-- name: ListLinearIssuesByTeam :many
SELECT id, team_id, title, description, assignee_id, state_id, url, created_at, updated_at, archived_at
FROM linear_issues
WHERE team_id = ? AND session_id = ?
ORDER BY created_at DESC
`

type ListLinearIssuesByTeamParams struct {
	TeamID    string `json:"team_id"`
	SessionID string `json:"session_id"`
}

type ListLinearIssuesByTeamRow struct {
	ID          string         `json:"id"`
	TeamID      string         `json:"team_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	AssigneeID  sql.NullString `json:"assignee_id"`
	StateID     sql.NullString `json:"state_id"`
	Url         string         `json:"url"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
	ArchivedAt  sql.NullInt64  `json:"archived_at"`
}

func (q *Queries) ListLinearIssuesByTeam(ctx context.Context, arg ListLinearIssuesByTeamParams) ([]ListLinearIssuesByTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, listLinearIssuesByTeam, arg.TeamID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinearIssuesByTeamRow{}
	for rows.Next() {
		var i ListLinearIssuesByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Title,
			&i.Description,
			&i.AssigneeID,
			&i.StateID,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinearStatesByTeam = `-- name: ListLinearStatesByTeam :many
SELECT id, name, type, team_id, created_at
FROM linear_states
WHERE team_id = ? AND session_id = ?
ORDER BY created_at ASC
`

type ListLinearStatesByTeamParams struct {
	TeamID    string `json:"team_id"`
	SessionID string `json:"session_id"`
}

type ListLinearStatesByTeamRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	TeamID    string `json:"team_id"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) ListLinearStatesByTeam(ctx context.Context, arg ListLinearStatesByTeamParams) ([]ListLinearStatesByTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, listLinearStatesByTeam, arg.TeamID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinearStatesByTeamRow{}
	for rows.Next() {
		var i ListLinearStatesByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.TeamID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinearTeams = `-- name: ListLinearTeams :many
SELECT id, name, key, created_at
FROM linear_teams
WHERE session_id = ?
ORDER BY created_at ASC
`

type ListLinearTeamsRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Key       string `json:"key"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) ListLinearTeams(ctx context.Context, sessionID string) ([]ListLinearTeamsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLinearTeams, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinearTeamsRow{}
	for rows.Next() {
		var i ListLinearTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Key,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinearUsers = `-- name: ListLinearUsers :many
SELECT id, name, email, created_at
FROM linear_users
WHERE session_id = ?
ORDER BY created_at ASC
`

type ListLinearUsersRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) ListLinearUsers(ctx context.Context, sessionID string) ([]ListLinearUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listLinearUsers, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinearUsersRow{}
	for rows.Next() {
		var i ListLinearUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLinearIssue = `-- name: UpdateLinearIssue :exec
UPDATE linear_issues
SET title = COALESCE(?, title),
    description = COALESCE(?, description),
    assignee_id = COALESCE(?, assignee_id),
    state_id = COALESCE(?, state_id),
    updated_at = ?
WHERE id = ? AND session_id = ?
`

type UpdateLinearIssueParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	AssigneeID  sql.NullString `json:"assignee_id"`
	StateID     sql.NullString `json:"state_id"`
	UpdatedAt   int64          `json:"updated_at"`
	ID          string         `json:"id"`
	SessionID   string         `json:"session_id"`
}

func (q *Queries) UpdateLinearIssue(ctx context.Context, arg UpdateLinearIssueParams) error {
	_, err := q.db.ExecContext(ctx, updateLinearIssue,
		arg.Title,
		arg.Description,
		arg.AssigneeID,
		arg.StateID,
		arg.UpdatedAt,
		arg.ID,
		arg.SessionID,
	)
	return err
}
