// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pagerduty.sql

package database

import (
	"context"
	"database/sql"
)

const createPagerDutyEscalationPolicy = `-- name: CreatePagerDutyEscalationPolicy :exec
INSERT INTO pagerduty_escalation_policies (id, name, session_id)
VALUES (?, ?, ?)
`

type CreatePagerDutyEscalationPolicyParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	SessionID string `json:"session_id"`
}

// Escalation Policies queries
func (q *Queries) CreatePagerDutyEscalationPolicy(ctx context.Context, arg CreatePagerDutyEscalationPolicyParams) error {
	_, err := q.db.ExecContext(ctx, createPagerDutyEscalationPolicy, arg.ID, arg.Name, arg.SessionID)
	return err
}

const createPagerDutyIncident = `-- name: CreatePagerDutyIncident :one
INSERT INTO pagerduty_incidents (id, title, service_id, urgency, status, body_details, session_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, service_id, urgency, status, body_details, created_at, updated_at
`

type CreatePagerDutyIncidentParams struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	ServiceID   string         `json:"service_id"`
	Urgency     string         `json:"urgency"`
	Status      string         `json:"status"`
	BodyDetails sql.NullString `json:"body_details"`
	SessionID   string         `json:"session_id"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

type CreatePagerDutyIncidentRow struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	ServiceID   string         `json:"service_id"`
	Urgency     string         `json:"urgency"`
	Status      string         `json:"status"`
	BodyDetails sql.NullString `json:"body_details"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

// Incidents queries
func (q *Queries) CreatePagerDutyIncident(ctx context.Context, arg CreatePagerDutyIncidentParams) (CreatePagerDutyIncidentRow, error) {
	row := q.db.QueryRowContext(ctx, createPagerDutyIncident,
		arg.ID,
		arg.Title,
		arg.ServiceID,
		arg.Urgency,
		arg.Status,
		arg.BodyDetails,
		arg.SessionID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreatePagerDutyIncidentRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ServiceID,
		&i.Urgency,
		&i.Status,
		&i.BodyDetails,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPagerDutyOnCall = `-- name: CreatePagerDutyOnCall :exec
INSERT INTO pagerduty_oncalls (id, user_email, escalation_policy_id, session_id)
VALUES (?, ?, ?, ?)
`

type CreatePagerDutyOnCallParams struct {
	ID                 string `json:"id"`
	UserEmail          string `json:"user_email"`
	EscalationPolicyID string `json:"escalation_policy_id"`
	SessionID          string `json:"session_id"`
}

// OnCalls queries
func (q *Queries) CreatePagerDutyOnCall(ctx context.Context, arg CreatePagerDutyOnCallParams) error {
	_, err := q.db.ExecContext(ctx, createPagerDutyOnCall,
		arg.ID,
		arg.UserEmail,
		arg.EscalationPolicyID,
		arg.SessionID,
	)
	return err
}

const createPagerDutyService = `-- name: CreatePagerDutyService :exec
INSERT INTO pagerduty_services (id, name, session_id)
VALUES (?, ?, ?)
`

type CreatePagerDutyServiceParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	SessionID string `json:"session_id"`
}

// Services queries
func (q *Queries) CreatePagerDutyService(ctx context.Context, arg CreatePagerDutyServiceParams) error {
	_, err := q.db.ExecContext(ctx, createPagerDutyService, arg.ID, arg.Name, arg.SessionID)
	return err
}

const deletePagerDutySessionData = `-- name: DeletePagerDutySessionData :exec
DELETE FROM pagerduty_incidents WHERE session_id = ?
`

// Session management
func (q *Queries) DeletePagerDutySessionData(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deletePagerDutySessionData, sessionID)
	return err
}

const getPagerDutyEscalationPolicyByID = `-- name: GetPagerDutyEscalationPolicyByID :one
SELECT id, name, created_at
FROM pagerduty_escalation_policies
WHERE id = ? AND session_id = ?
`

type GetPagerDutyEscalationPolicyByIDParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
}

type GetPagerDutyEscalationPolicyByIDRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) GetPagerDutyEscalationPolicyByID(ctx context.Context, arg GetPagerDutyEscalationPolicyByIDParams) (GetPagerDutyEscalationPolicyByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPagerDutyEscalationPolicyByID, arg.ID, arg.SessionID)
	var i GetPagerDutyEscalationPolicyByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getPagerDutyIncidentByID = `-- name: GetPagerDutyIncidentByID :one
SELECT id, title, service_id, urgency, status, body_details, created_at, updated_at
FROM pagerduty_incidents
WHERE id = ? AND session_id = ?
`

type GetPagerDutyIncidentByIDParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
}

type GetPagerDutyIncidentByIDRow struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	ServiceID   string         `json:"service_id"`
	Urgency     string         `json:"urgency"`
	Status      string         `json:"status"`
	BodyDetails sql.NullString `json:"body_details"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

func (q *Queries) GetPagerDutyIncidentByID(ctx context.Context, arg GetPagerDutyIncidentByIDParams) (GetPagerDutyIncidentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPagerDutyIncidentByID, arg.ID, arg.SessionID)
	var i GetPagerDutyIncidentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ServiceID,
		&i.Urgency,
		&i.Status,
		&i.BodyDetails,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPagerDutyOnCallByID = `-- name: GetPagerDutyOnCallByID :one
SELECT id, user_email, escalation_policy_id, created_at
FROM pagerduty_oncalls
WHERE id = ? AND session_id = ?
`

type GetPagerDutyOnCallByIDParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
}

type GetPagerDutyOnCallByIDRow struct {
	ID                 string `json:"id"`
	UserEmail          string `json:"user_email"`
	EscalationPolicyID string `json:"escalation_policy_id"`
	CreatedAt          int64  `json:"created_at"`
}

func (q *Queries) GetPagerDutyOnCallByID(ctx context.Context, arg GetPagerDutyOnCallByIDParams) (GetPagerDutyOnCallByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPagerDutyOnCallByID, arg.ID, arg.SessionID)
	var i GetPagerDutyOnCallByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.EscalationPolicyID,
		&i.CreatedAt,
	)
	return i, err
}

const getPagerDutyServiceByID = `-- name: GetPagerDutyServiceByID :one
SELECT id, name, created_at
FROM pagerduty_services
WHERE id = ? AND session_id = ?
`

type GetPagerDutyServiceByIDParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
}

type GetPagerDutyServiceByIDRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) GetPagerDutyServiceByID(ctx context.Context, arg GetPagerDutyServiceByIDParams) (GetPagerDutyServiceByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPagerDutyServiceByID, arg.ID, arg.SessionID)
	var i GetPagerDutyServiceByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listPagerDutyEscalationPolicies = `-- name: ListPagerDutyEscalationPolicies :many
SELECT id, name, created_at
FROM pagerduty_escalation_policies
WHERE session_id = ?
ORDER BY created_at ASC
`

type ListPagerDutyEscalationPoliciesRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) ListPagerDutyEscalationPolicies(ctx context.Context, sessionID string) ([]ListPagerDutyEscalationPoliciesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPagerDutyEscalationPolicies, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPagerDutyEscalationPoliciesRow{}
	for rows.Next() {
		var i ListPagerDutyEscalationPoliciesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagerDutyIncidents = `-- name: ListPagerDutyIncidents :many
SELECT id, title, service_id, urgency, status, body_details, created_at, updated_at
FROM pagerduty_incidents
WHERE session_id = ?
ORDER BY created_at DESC
`

type ListPagerDutyIncidentsRow struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	ServiceID   string         `json:"service_id"`
	Urgency     string         `json:"urgency"`
	Status      string         `json:"status"`
	BodyDetails sql.NullString `json:"body_details"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

func (q *Queries) ListPagerDutyIncidents(ctx context.Context, sessionID string) ([]ListPagerDutyIncidentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPagerDutyIncidents, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPagerDutyIncidentsRow{}
	for rows.Next() {
		var i ListPagerDutyIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ServiceID,
			&i.Urgency,
			&i.Status,
			&i.BodyDetails,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagerDutyIncidentsByStatus = `-- name: ListPagerDutyIncidentsByStatus :many
SELECT id, title, service_id, urgency, status, body_details, created_at, updated_at
FROM pagerduty_incidents
WHERE status = ? AND session_id = ?
ORDER BY created_at DESC
`

type ListPagerDutyIncidentsByStatusParams struct {
	Status    string `json:"status"`
	SessionID string `json:"session_id"`
}

type ListPagerDutyIncidentsByStatusRow struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	ServiceID   string         `json:"service_id"`
	Urgency     string         `json:"urgency"`
	Status      string         `json:"status"`
	BodyDetails sql.NullString `json:"body_details"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

func (q *Queries) ListPagerDutyIncidentsByStatus(ctx context.Context, arg ListPagerDutyIncidentsByStatusParams) ([]ListPagerDutyIncidentsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listPagerDutyIncidentsByStatus, arg.Status, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPagerDutyIncidentsByStatusRow{}
	for rows.Next() {
		var i ListPagerDutyIncidentsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ServiceID,
			&i.Urgency,
			&i.Status,
			&i.BodyDetails,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagerDutyOnCalls = `-- name: ListPagerDutyOnCalls :many
SELECT id, user_email, escalation_policy_id, created_at
FROM pagerduty_oncalls
WHERE session_id = ?
ORDER BY created_at ASC
`

type ListPagerDutyOnCallsRow struct {
	ID                 string `json:"id"`
	UserEmail          string `json:"user_email"`
	EscalationPolicyID string `json:"escalation_policy_id"`
	CreatedAt          int64  `json:"created_at"`
}

func (q *Queries) ListPagerDutyOnCalls(ctx context.Context, sessionID string) ([]ListPagerDutyOnCallsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPagerDutyOnCalls, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPagerDutyOnCallsRow{}
	for rows.Next() {
		var i ListPagerDutyOnCallsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.EscalationPolicyID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagerDutyServices = `-- name: ListPagerDutyServices :many
SELECT id, name, created_at
FROM pagerduty_services
WHERE session_id = ?
ORDER BY created_at ASC
`

type ListPagerDutyServicesRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) ListPagerDutyServices(ctx context.Context, sessionID string) ([]ListPagerDutyServicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPagerDutyServices, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPagerDutyServicesRow{}
	for rows.Next() {
		var i ListPagerDutyServicesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePagerDutyIncidentStatus = `-- name: UpdatePagerDutyIncidentStatus :exec
UPDATE pagerduty_incidents
SET status = ?,
    updated_at = ?
WHERE id = ? AND session_id = ?
`

type UpdatePagerDutyIncidentStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) UpdatePagerDutyIncidentStatus(ctx context.Context, arg UpdatePagerDutyIncidentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePagerDutyIncidentStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.SessionID,
	)
	return err
}
