// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resend.sql

package database

import (
	"context"
	"database/sql"
)

const createResendEmail = `-- name: CreateResendEmail :exec
INSERT INTO resend_emails (id, from_email, to_emails, subject, html, cc_emails, bcc_emails, reply_to, session_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateResendEmailParams struct {
	ID        string         `json:"id"`
	FromEmail string         `json:"from_email"`
	ToEmails  string         `json:"to_emails"`
	Subject   string         `json:"subject"`
	Html      string         `json:"html"`
	CcEmails  sql.NullString `json:"cc_emails"`
	BccEmails sql.NullString `json:"bcc_emails"`
	ReplyTo   sql.NullString `json:"reply_to"`
	SessionID string         `json:"session_id"`
}

func (q *Queries) CreateResendEmail(ctx context.Context, arg CreateResendEmailParams) error {
	_, err := q.db.ExecContext(ctx, createResendEmail,
		arg.ID,
		arg.FromEmail,
		arg.ToEmails,
		arg.Subject,
		arg.Html,
		arg.CcEmails,
		arg.BccEmails,
		arg.ReplyTo,
		arg.SessionID,
	)
	return err
}

const deleteResendSessionData = `-- name: DeleteResendSessionData :exec
DELETE FROM resend_emails WHERE session_id = ?
`

func (q *Queries) DeleteResendSessionData(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteResendSessionData, sessionID)
	return err
}

const getResendEmailByID = `-- name: GetResendEmailByID :one
SELECT id, from_email, to_emails, subject, html, cc_emails, bcc_emails, reply_to, created_at
FROM resend_emails
WHERE id = ? AND session_id = ?
`

type GetResendEmailByIDParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
}

type GetResendEmailByIDRow struct {
	ID        string         `json:"id"`
	FromEmail string         `json:"from_email"`
	ToEmails  string         `json:"to_emails"`
	Subject   string         `json:"subject"`
	Html      string         `json:"html"`
	CcEmails  sql.NullString `json:"cc_emails"`
	BccEmails sql.NullString `json:"bcc_emails"`
	ReplyTo   sql.NullString `json:"reply_to"`
	CreatedAt int64          `json:"created_at"`
}

func (q *Queries) GetResendEmailByID(ctx context.Context, arg GetResendEmailByIDParams) (GetResendEmailByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getResendEmailByID, arg.ID, arg.SessionID)
	var i GetResendEmailByIDRow
	err := row.Scan(
		&i.ID,
		&i.FromEmail,
		&i.ToEmails,
		&i.Subject,
		&i.Html,
		&i.CcEmails,
		&i.BccEmails,
		&i.ReplyTo,
		&i.CreatedAt,
	)
	return i, err
}

const listResendEmails = `-- name: ListResendEmails :many
SELECT id, from_email, to_emails, subject, created_at
FROM resend_emails
WHERE session_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListResendEmailsParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
}

type ListResendEmailsRow struct {
	ID        string `json:"id"`
	FromEmail string `json:"from_email"`
	ToEmails  string `json:"to_emails"`
	Subject   string `json:"subject"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) ListResendEmails(ctx context.Context, arg ListResendEmailsParams) ([]ListResendEmailsRow, error) {
	rows, err := q.db.QueryContext(ctx, listResendEmails, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResendEmailsRow{}
	for rows.Next() {
		var i ListResendEmailsRow
		if err := rows.Scan(
			&i.ID,
			&i.FromEmail,
			&i.ToEmails,
			&i.Subject,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
